### ISSUE TITLE
Use a different pkg-config program

### ISSUE THREAD

**Issue by jpcima** [DISTRHO/DPF#102]
Hi. Please allow the location of the `pkg-config` program to be user-defined.
eg. permit such a command as `make PKG_CONFIG=i686-w64-mingw32-pkg-config`
There exist several cross-compiling environments for Windows and Mac which provide their pkg-config wrappers.

**Comment by osch** [comment]
Hi, I prepared a simple patch (#103) for providing such a command as `make PKG_CONFIG=i686-w64-mingw32-pkg-config`.

**Comment by falkTX** [comment]
Fixed in develop branch.
Note for mingw, you likely will need to use something like:
```
export PKG_CONFIG="i686-w64-mingw32-pkg-config --static"
```
