### ISSUE TITLE
Modal dialog not trully modal

### ISSUE THREAD

**Issue by iurienistor** [DISTRHO/DPF#106]
I have installed 3d Band EQ. When I open the dialog About I have the following:
* Can't access the parent widget area - which is ok, behaves like modal
* Still can access the parent/main window and close it

Either it was designed like this, or the opened new window must be really modal. I suspect that this comes from pugl or interaction with it. When a modal is created it must disable the main window too, not only the widget. The modality should be propagated to pugl  too probably.

**Comment by falkTX** [comment]
It is intentionally to let the parent window be closed.
Plugin UIs must not block the main loop, and need to handle being closed by the user or host at any point. So it is normal that the main window is accessible.
What is the issue here actually?

**Comment by iurienistor** [comment]
It is not a big issue. The point is when creating a modal window, it should block the user input to its parent. The host can still close the parent and its child too. The input of the main widget area is now blocked, but not of the main window, the user is still able to close the main window, i.e. access its input. From Wikipedia here is the definition of a modal behaviour:  "a modal window is a graphical control element subordinate to an application's main window. It creates a mode that disables the main window, but keeps it visible with the modal window as a child window in front of it. Users must interact with the modal window before they can return to the parent application. This avoids interrupting the workflow on the main window. Modal windows are sometimes called heavy windows or modal dialogs because they often display a dialog box. "

**Comment by falkTX** [comment]
But that is the point of the modals in DPF.
If you try to click or do any action with the window behind the modal, the input is redirected to the modal.
The only possible action in the main window is to close it, or resize the window perhaps (depends on the OS).
