### ISSUE TITLE
DSSI memory leak

### ISSUE THREAD

**Issue by Lyberta** [DISTRHO/DPF#11]
So I've run Rosegarden with my plugins in DSSI format under GDB. When I closed the app I saw this in a terminal:

**\* Leaked objects detected: 4 instance(s) of class 'PluginExporter'
**\* Leaked objects detected: 4 instance(s) of class 'Plugin'

So I assume the DPF doesn't properly clean after itself.

**Comment by falkTX** [comment]
I find it very, very unlikely for that to happen.
see https://github.com/DISTRHO/DPF/blob/master/distrho/src/DistrhoPluginLADSPA%2BDSSI.cpp#L413
