### ISSUE TITLE
Make AU DSP actually process audio

### ISSUE THREAD

**Issue by falkTX** [DISTRHO/DPF#113]

**Comment by zamaudio** [comment]
See PR #116

**Comment by zamaudio** [comment]
With a getter method that will return the expected number of channels that the plugin supports, in addition to 2-2 and 1-1 we can make it process multi-mono on a stereo channel.

**Comment by falkTX** [comment]
Confirmed to work in Renoise and the Gain example plugin.
We now correctly set the number of inputs and outputs, which ends up in audio being processed correctly as well.
