### ISSUE TITLE
Flags for native OSX build of AU

### ISSUE THREAD

**Issue by zamaudio** [DISTRHO/DPF#120]
https://github.com/DISTRHO/DPF/blob/a291737aef87bfbac914f004bcf3f36bea80affc/Makefile.plugins.mk#L355

This line wont do much.. it should be `-isysroot ...` not `-I ...` but I think it would break cross compiling.

**Comment by falkTX** [comment]
There is `-i` and `-I`, one of them I believe to be the same as `-isysroot`.
Do you know what `-isysroot` does? Last time I looked it up, it just adds an include path that will ignore compiler warnings from.

**Comment by zamaudio** [comment]
I believe `-isysroot` is equivalent to changing the path that the compiler was built to look in system paths for

**Comment by zamaudio** [comment]
Added $(REZ_FLAGS), issue closed
