### ISSUE TITLE
Window::onClose callback not called in Window::close() ?

### ISSUE THREAD

**Issue by pdesaulniers** [DISTRHO/DPF#136]
`Window::close()` does not trigger `Window::onClose`.

Is this done on purpose? It seems like the window is only hidden in this function. However, the name of the method implies that the window is closed, so I expected `Window::onClose` to be called.

**Comment by falkTX** [comment]
Might be something I missed, as we usually only have a single window in plugins.
What is the usecase that you have where this is an issue?

**Comment by pdesaulniers** [comment]
I'm using a window for the context menu in my plugins (which use a heavily butchered version of DPF :) ). 

I just needed to put the selected item index to -1 on close, so that I don't see a selected entry when I reopen the menu. 

This issue can wait for now.

(on a side note: I'll try cleaning this widget up and porting it to vanilla DPF at some point, since I believe it's really useful. It could be based on a ContextWindow, which is just a Window without decorations that can be positioned anywhere)

**Comment by falkTX** [comment]
Clarified in https://github.com/DISTRHO/DPF/blob/8a702163118c693da96dca625573784f9637e729/dgl/Window.hpp#L371

onClose to to notify of close event request, so that you can cancel it or confirm it (by default it confirms it).

also clarified that plugin windows will never receive such request.
