### ISSUE TITLE
Implement mouse cursor manipulation

### ISSUE THREAD

**Issue by pdesaulniers** [DISTRHO/DPF#142]
A small thing that can make plugin UIs look more polished is mouse cursor manipulation.

The following features would be nice:
- Setting the cursor style on hovering a widget, including an 'hidden' style.
- Cursor warping. For instance, when turning a knob, we might want to hide the cursor, and make it reappear on the knob on mouse up.
- Constraining the cursor to a rectangle. This is good to avoid confusion in some cases when the cursor is hidden.

These features have been implemented to some extent in Wolf Shaper, but the code is quite dirty, and doesn't handle all corner cases yet. It also doesn't work on MacOS for now.

Still, this is something I would love to have in upstream DPF.

**Comment by falkTX** [comment]
PR is welcome for this.
Though personally I dislike when applications try to use custom cursor icons, would be nice if we can find a way to just set the system ones.

**Comment by pdesaulniers** [comment]
In case someone wants to implement this:

> Setting the cursor style on hovering a widget, including an 'hidden' style.

Upstream pugl appears to support this since https://github.com/lv2/pugl/pull/36 (except the 'hidden' style, I guess?)

> Cursor warping

This can be done using [SetCursorPos](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setcursorpos) on Win32, [XWarpPointer](https://tronche.com/gui/x/xlib/input/XWarpPointer.html) on X11, and probably [CGWarpMouseCursorPosition](https://developer.apple.com/documentation/coregraphics/1456387-cgwarpmousecursorposition?language=objc) on MacOS (I don't know much about this OS!)

> Constraining the cursor to a rectangle. This is good to avoid confusion in some cases when the cursor is hidden.

I don't recommend exposing this feature anymore, as it leads to some pretty messy code. Instead, a nicer API would be to allow switching the mouse into 'relative' mode (like [SDL_SetRelativeMouseMode in SDL2](https://wiki.libsdl.org/SDL_SetRelativeMouseMode)):

```
While the mouse is in relative mode, the cursor is hidden, 
and the driver will try to report continuous motion in the current window. 
Only relative motion events will be delivered, the mouse position will not change.
```
...which, I think, would be perfect for implementing this:

>  when turning a knob, we might want to hide the cursor, and make it reappear on the knob on mouse up

because, otherwise, the cursor might hit the corner of the screen while we turn the knob...

**Comment by falkTX** [comment]
This is available on latest DPF, both Window and TopLevelWidget have a method called `setCursor`.
