### ISSUE TITLE
Please remove --as-needed in the link line

### ISSUE THREAD

**Issue by yurivict** [DISTRHO/DPF#145]
https://github.com/DISTRHO/DPF/blob/68b3a57a78d814810972584ed571662fe5cfb8f0/Makefile.base.mk#L100

The ```--as-needed``` is to hide missing symbols. It should only be used in special cases, not here. ```zam-plugins``` builds fine with this flag removed, and everything else should also build fine.

**Comment by falkTX** [comment]
it does not hurt to have it, so I do not see a reason to remove it

**Comment by yurivict** [comment]
ok

**Comment by yurivict** [comment]
Actually, it does hurt when used when not needed. When some symbol is missing, ```--as-needed``` would hide this fact at the build-time until the run-time. ```--as-needed``` should only be used in sime special situations when symbols can be resolved by libraries loaded by users, and not the project itself. An LV2 plugin doesn't introduce such situation.

**Comment by falkTX** [comment]
That is not correct, as DPF also uses `-Wl,--no-undefined` which detects that case
