### ISSUE TITLE
Multiple lv2lint problems

### ISSUE THREAD

**Issue by jpcima** [DISTRHO/DPF#149]
The following errors are seen, when running lv2lint on DPF examples.

- [x]  Options Iface
          opts:interface not defined
          seeAlso: <http://lv2plug.in/ns/ext/options#interface>
- [x]  State
          state:interface not returned by 'extension_data'
          seeAlso: <http://lv2plug.in/ns/ext/state#interface>
- [x]  Worker
          work:interface has no 'work_response' function
          seeAlso: <http://lv2plug.in/ns/ext/worker#interface>
- [x]  Resize Interface
          lv2:extensionData ui:resize missing
          seeAlso: <http://lv2plug.in/ns/extensions/ui#resize>

Moreover it's complaining when license is not specified as URI, which would be a defect of the examples and not of DPF itself.

- [ ]  License
          doap:license not a URI
          seeAlso: <http://usefulinc.com/ns/doap#license>

**Comment by falkTX** [comment]
Good stuff, I need to install lv2lint myself so I can keep track of these things.
Do you mind creating the same ticket against DISTRHO-Ports? thanks

For the license, I always though simple text was a valid value to use in there. does it really have to be a URI?

**Comment by jpcima** [comment]
>For the license, I always thought simple text was a valid value to use in there. does it really have to be a URI?

The property describes as: "The URI of an RDF description of the license the software is distributed under. E.g. a SPDX reference"

[Reference](http://usefulinc.com/ns/doap)

**Comment by falkTX** [comment]
Now fixed in develop branch.
lv2lint is part of the example-plugins CI tests, where this CI file is usable to test other plugins / projects in general.
See https://github.com/DISTRHO/DPF/runs/3640475589?check_suite_focus=true for a test run.

Will add in runtime check, just need to see why carla from PPA leaks memory but my local one does not..
