### ISSUE TITLE
[macOS VST] Major problems when plugin UI is re-opened

### ISSUE THREAD

**Issue by ARival** [DISTRHO/DPF#153]
Latest Mojave:
Load up any VST built on macOS for macOS, close the plugin window and attempt to re-open it.

Results -
Ableton Live: Bugs out the entire UI, causes program to hang on exit
Audacity: hard locks
Minihost Modular: Plugin UI becomes a black screen

**Comment by falkTX** [comment]
Fixed on develop branch, but not in the best way.
I will see about the best possible case for this, it is a tricky one

**Comment by falkTX** [comment]
Proper fix in fc96e9fd894df36e45aaacac209ca7078ff0629d

I was able to reproduce the issue, and then fix it.
FLStudio had the same problem as they seem to use OpenGL for the macOS GUI, just like Ableton.

![image](https://user-images.githubusercontent.com/1334853/136098793-ec038209-dfcd-4592-8f45-7763e1abe5d3.png)
