### ISSUE TITLE
FR: Add parameter property to set the LV2 port comment property

### ISSUE THREAD

**Issue by SpotlightKid** [DISTRHO/DPF#164]
Some hosts (e.g. Ardour) use this to show a tooltip for the parameter in the generic UI.

![ardour-lv2-port-doc](https://user-images.githubusercontent.com/5719151/62389464-2f814680-b560-11e9-8a42-f85be32000dc.png)

**Comment by jpcima** [comment]
If this the `rdfs:comment` property?
For the `lv2:documentation` property, I don't get a tooltip from Ardour (version 5).

**Comment by SpotlightKid** [comment]
Yes, sorry, you are right, I neglected to check NY wrong assumption.

Host probably should display the documentation property too, but that's a different issue :)

**Comment by falkTX** [comment]
This has been merged now
