### ISSUE TITLE
Running lv2-ttl-generator on ZynAddSubFX.so produces random pset:value in prests.ttl

### ISSUE THREAD

**Issue by plater** [DISTRHO/DPF#18]
Trying to create reproducible builds in ZynAddSubFX, I've stumbled upon a strange bug. During the build process lv2-ttl-generator is run on each of ZynAddSubFX's plugin's and when run on ZynAddSubFX.so itself the value of "lv2:port [ lv2:symbol "osc_port" ; pset:value 14366.000000 ; ]  ." in presets.ttl produces a seemingly random pset:value. Can you point me in the direction of where this value is derived? I suspect that this is most probably a ZynAddSubFX issue but the source forge bug page doesn't seem to have much movement.

**Comment by falkTX** [comment]
this is "normal", as that's a random value for an output control port.
A related commit is https://github.com/DISTRHO/DPF/commit/e0d8e14a14d407648768da7e34bcf31812245387
For presets, control outputs should not be added, I guess a check similar to that commit is needed.

**Comment by plater** [comment]
so if this isn't a fault I can safely use the same presets.ttl for each build of the same ZynAddSubFX version, this will solve my problem.
I patched DPF in the zyn sources to yesterday's git, I just looked through the patch and that commit isn't in it. Strange thing is none of the other plugins have this problem.
I'll have a better look tomorrow.
Thanks for the prompt reply.

**Comment by falkTX** [comment]
This will be fixed the next time zynaddsubfx updates DPF submodule.

**Comment by plater** [comment]
Works like a charm, thanks for the quick fix.
