### ISSUE TITLE
LV2 preset does not export bypass correctly

### ISSUE THREAD

**Issue by jpcima** [DISTRHO/DPF#186]
Hi, I discovered the preset exporter to be affected as well by a bypass issue.
On recalling a preset, this message appears: `error: Preset port 'dpf_bypass' is missing`

As it appears, the exporter needs also to receive the usual treatment.
- exchange `dpf_bypass` with `lv2_enabled`
- invert the default value

**Comment by falkTX** [comment]
Fixed by your own commit, imported as 8616522d5a13398fda032393780f5749d47192fc
