### ISSUE TITLE
No plugin window enabled on different VST hosts

### ISSUE THREAD

**Issue by webpolis** [DISTRHO/DPF#187]
Hi

I've set the following flags:

```
#define DISTRHO_PLUGIN_HAS_UI          1
#define DISTRHO_PLUGIN_HAS_EMBED_UI    0
#define DISTRHO_PLUGIN_HAS_EXTERNAL_UI 1
```

Based on the ExternalUI example, but using 2 different VST hosts, there is no way to open the plugin's window. Other VST work, the hosts enable their respective "plugin window/editor" buttons.

How is that DPF notifies the host that there is a UI / custom window available?

I'm testing a custom variant of `ExternalWindow.hpp` that tries to support Windows. See https://gist.github.com/webpolis/b62042f305ef281aa5cf042ed7517e86

**Comment by falkTX** [comment]
Such thing does not exist for VST, it needs to embed the window.

**Comment by webpolis** [comment]
Lol, I'm new in VST development.

Ok, in that case, where/when do you think is a good idea to open the external app? Which event is best? And, at which event is best to close the external process?

I'm experimenting, so I'm forced to use an external app.

Thanks! 

btw, DPF rocks.

**Comment by webpolis** [comment]
Perhaps... I'd enable the embedded UI, and catch the "open UI" event somehow, and open my process... and do the same for the "close moment". What are your thoughts? What's your advise?

**Comment by falkTX** [comment]
If you use DSSI, LV2 or JACK (standalone) formats, you will have your external window.
It is just that the VST spec does not support it.

If you really need VST for some reason, the best you can do is to create a dummy plugin window, which inside contains a button that will open an external window when clicked.

**Comment by webpolis** [comment]
@falkTX is there any reason why `createPlugin` is called twice when opening a VST dll?

I have a string printed out at plugin creation

```
Plugin* createPlugin()
{
    std::cout << "createPlugin" << std::endl;
    return new MyPlugin();
}
```

And I get that string twice, loading using **vsthost** or **Cantabile**. My code is based on the examples in DPF, there's no extra magic being done.

**Comment by webpolis** [comment]
And the UI class' constructor is called 3 times once I open the plugin editor in the host

```
    MyPluginUI()
        : UI(405, 150)
    {
        setGeometryConstraints(405, 150, true);
        std::cout << "MyPluginUI" << std::endl;
    }

```

Like said, no extra work done. It's a copy of the Meters example.

**Comment by falkTX** [comment]
The first instance of the plugin is a static one, created so we can extract information about the plugin (number of audio ports, parameters, synth or not, etc)
The same happens for LADSPA/DSSI version, as we need to extract this data there too.
LV2 does this too, but during post-compilation time for generating the ttl.

On the VST, the UI is created when the host asks about the size of the UI.
DPF does not know this information if an UI has not been created yet, so DPF creates a temporary window. Sadly this has to be deleted and cannot be reused, as the platform-window pointer is not set during this call.
It is a very nasty thing that VST does, not sure if because Windows API demand or what the reason really is, but yeah it is something required by VST.
Some hosts are nice and create a big window, call VST UI open and only then ask about the UI size.

VST is quite the ugly spec, so you will find these sorta things all over the place...

**Comment by webpolis** [comment]
Thanks. Really introductory.

I agree, as far as I can tell by reading the VST SDK documentation and
looking around, it is not a great piece if engineering.

On Fri, Oct 18, 2019, 1:46 PM Filipe Coelho <notifications@github.com>
wrote:

> The first instance of the plugin is a static one, created so we can
> extract information about the plugin (number of audio ports, parameters,
> synth or not, etc)
> The same happens for LADSPA/DSSI version, as we need to extract this data
> there too.
> LV2 does this too, but during post-compilation time for generating the ttl.
>
> On the VST, the UI is created when the host asks about the size of the UI.
> DPF does not know this information if an UI has not been created yet, so
> DPF creates a temporary window. Sadly this has to be deleted and cannot be
> reused, as the platform-window pointer is not set during this call.
> It is a very nasty thing that VST does, not sure if because Windows API
> demand or what the reason really is, but yeah it is something required by
> VST.
> Some hosts are nice and create a big window, call VST UI open and only
> then ask about the UI size.
>
> VST is quite the ugly spec, so you will find these sorta things all over
> the place...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <http://email.arpado.site/c/eJxFUMuOgkAQ_Bq8aZyXjAcOMyAOIA-RnVEvBnFUfGFk3MS_X9TDJp1OdaorXV07pwS4skGvdlwmIkIQMQZw-4zCqU-Ph9f9TlC4qSc5n47nJi6LE_s1S-Oeqk3_YOHhtawvg8OnV821d3Qg1QBtKbW1hsOhTRAcjyjY7ynRcKfLXe_iHI25txZiFvS7OtTm-Ny-1d3gBYsiF-kbZW-ybtunbjsAqG0hX78Pbdrm-ai0hbxbY-p9XZWmbm7d0uhLm-asbx3LWOATkbpFEkeZ4ixxvSDIvHkmcrtgxE38RYxDziBbRqsVyhKpVISKnxmBYoE9X-aT5RQjGUuuRmiWxHIpwqjwEqIUXM_SNM_UYj1NJ1x6oRdYEH3cdo9c9c30CUYUAUBB7-E89P3ysiD_WopFHM4jKSOmElu5OUEKq3kxkTwRguNM-RJ30X5Eg_94_gD9noMm>,
> or unsubscribe
> <http://email.arpado.site/c/eJxFj1FrgzAAhH-NvrWoSap58CER00yr0060b8XYTNNZFY2D_vu5MhgcB3fwwd3Nr23YuLap_IDwGCGAtLap-wWiI_O69jlNCERXFZ7pEec6qYs7-dYXHdyb6641oPWoVb9vX96MD7PzDwJjz8MCNRaGDnCklJ4AwsOuPFg3aZm932k9LQYghsM2tUp3q_iltzCMWn2qptZqHJYtr8OyiqWZlZC7etXdVhHyxhBPilMBk1P4DnlSsSADecbPbkHSIGUfCYwocciFmLM_y6l_Gg79w3gS5XFZxqRK3So4I1DBKi_CkqacU5hVrITbqxe0_1_2A-ayW70>
> .
>



To unsubscribe click: <http://email.arpado.site/u/eJwdzU0LgjAAgOFfo7fCfbU87LBJuhQjI1w30W1-pSSygv594eW9vTyG1QBrCvyBRVxmhCDiHBD0idIkPvbdd1kISqvhdBNJWLi8vo_84x4uGnW16zwczPUw7but-jX7PTOaImND01pzaAOLQxJSYGETBJo0EGF_Zatdpq8HBefnmMhc5mmRlWXG1YWq6EaQwqq4n0pxkVLgq4pL_Ie2ad8Nrn83G-WYB_kPLs062A>

**Comment by webpolis** [comment]
Thanks. Really introductory.

I agree, as far as I can tell by reading the VST SDK documentation and
looking around, it is not a great piece of engineering.
