### ISSUE TITLE
Add support for effEditKeyDown and effEditKeyUp

### ISSUE THREAD

**Issue by fundamental** [DISTRHO/DPF#19]
Some VST hosts do not reliably relay keyboard events to the plugin, with one notable example being FL Studio. From researching this issue it appears that some (deprecated) VST opcodes are used to send the messages instead. I would ask that effEditKeyDown (59) and effEditKeyUp (60) are added to support keyboard events under these hosts. 

Information is scattered around the net about these particular opcodes (one example for reference https://forum.juce.com/t/vst-plugin-still-not-getting-keystrokes/6582/14 ). So, it should be possible to add this without too much of a headache.

**Comment by falkTX** [comment]
I did a quick commit on DPF in order to support this.
https://github.com/DISTRHO/DPF/commit/fa54750583225c2e6aa5cda9baf9c18eb722daee

Completely untested. I don't have enough time to dig deeper into this, but that should give you enough to work with for now.

**Comment by fundamental** [comment]
Thanks. I'll add this to the windows build and I'll report back if the commit is successful or not.

**Comment by fundamental** [comment]
It looks like most of the patch works, though there are some remaining issues.

- Duplicate key presses are observed in hosts which support both effEditKeyDown and normal window events. I'd suggest ignoring effEditKeyDown events when events are observed via the normal window interface. (Reaper is an example of an affected host)
- Special Key presses (notably shift and control) are not handled correctly. Shift for example is incorrectly interpreted as a space key press.
- The effEditKeyDown/Up commit breaks the build for VST plugins which use an external/out-of-process UI (i.e. zyn's ntk UI). I would expect the correct way to handle this would to just be to disable the extra event handling in the out-of-process UI case.

See https://www.kvraudio.com/forum/viewtopic.php?t=488363&p=6839472#p6839472 for the original user feedback.

Thanks again for the fast implementation.

**Comment by falkTX** [comment]
There should be a way to detect if the host uses those vst keys or not, perhaps a can-do return...
If not, we just hardcode a whitelist of hosts and keep adding more as needed.
Will have to investigate later.

Considering I did no tests on this code at all (only that it builds), I'm surprised some things actually work :)
There's a few things I believe you're able to fix yourself maybe,
if you can then please do and send a PR to DPF later.

**Comment by SpotlightKid** [comment]
This can be closed, can it not? PR #20 is closed.

**Comment by falkTX** [comment]
it does not work fully right yet. plus we have to start whitelisting good known hosts.
right now keys are getting duplicated in some of them.

**Comment by falkTX** [comment]
@fundamental I would like to close this issue, by doing whatever is missing now for it.
Can you tell me what is the status of zyn against it?
My idea is to really have a white list of hosts that need this, it should not be many.
Also note that there was a typo on code related to this, leading to some special keys being sent to UIs as normal keys (and I guess producing weird results)

**Comment by fundamental** [comment]
Sure thing. It might take a bit of digging to jog my memory, so I'll work on figuring out the bits this week. IIRC I was unable to test due to the affected hosts, though I'll look through my old notes to see if I was mistaken. If I don't have a proper response by start-of-day Wednesday, remind me.

**Comment by fundamental** [comment]
Zyn should be consuming the effKeyUp/Down messages. I recall there were some oddities with respect to special keys. Additionally, it's a mixed bag is hosts provide the functionality or not. Looking through my notes I don't have a list of good/bad hosts. It should be fine to have this issue closed for the time being. If I have specific feedback I'll try to narrow in on the issue and open a new issue.
