### ISSUE TITLE
don't hardcode -msse and -msse2 for non-x86 platforms

### ISSUE THREAD

**Issue by BrainDamage** [DISTRHO/DPF#190]
https://github.com/DISTRHO/DPF/blob/4c8d448b10eeeb55f507b6e55e6095e108560fe6/Makefile.base.mk#L109
hardcodes -msse and -msse2 build flags for every architecture, forcing one building DPF on platforms such as arm to manually edit the file instead of just settings CFLAGS to set optimizations like one would espect normally.
Please edit the file so that those two flags are appended just for x86 systems, the rest of the platforms can at least append their own without editing files this way

**Comment by SpotlightKid** [comment]
Isn't this fixed now by #191?

**Comment by falkTX** [comment]
Yes it is :)

I need to do the same for Carla and Cadence projects at some point too
