### ISSUE TITLE
Port groups

### ISSUE THREAD

**Issue by jpcima** [DISTRHO/DPF#192]
It will be interesting to support the Port Groups feature of LV2 in DPF.

- a port group has a name and a symbol;
- a port group is input or output, and additionally may inherit from a predefined class of the specification;
- a parameter or audio port belongs to zero, one (or more?) port group(s).

I have started to think how it is best implemented, and I wondered about this:
may ports belong in multiple groups? does it ever make sense?

Edit: some information relevant to port groups in various plugin formats
https://forum.juce.com/t/plug-in-parameter-groups/29409

**Comment by falkTX** [comment]
A port can only belong to a single group.
It does not have to be input or output, that should not matter. whatever it is in/out depends on which port it gets associated with.

**Comment by falkTX** [comment]
Implemented in 495dcc4f03d6a2ed0d30c56c885e4eb7476f4488.
