### ISSUE TITLE
Mac plugin dylib links to itself

### ISSUE THREAD

**Issue by jpcima** [DISTRHO/DPF#197]
Hi, when I build a plugin using Mac, the dylib file appears to have a link to itself.
It is seen on the second line of `otool -L file.dylib`. VST has it, and also both LV2 libraries.
Using `Apple LLVM version 8.1.0 (clang-802.0.42)`.

```
string-machine:
	../../bin/string-machine-vst.dylib (compatibility version 0.0.0, current version 0.0.0)
```

It does not prevent the plugin from loading in hosts.
But because of this bizarre occurrence, I'm not able to use the tool [macdylibbundler](https://github.com/auriamg/macdylibbundler).

It will produce the following:
```
* Collecting dependencies...
/!\ WARNING : Cannot resolve path '../../bin/string-machine.lv2/string-machine_dsp.dylib'

/!\ WARNING : Library string-machine_dsp.dylib has an incomplete name (location unknown)
Please specify now the directory where this library can be found (or write 'quit' to abort): ^C
```

**Comment by jpcima** [comment]
A question: are Mac plugins not supposed to be linked as `-bundle`, instead of `-dynamiclib`?
When bundle is generated, I don't encounter such problems.

This documents dynamic libraries vs loadable modules (aka bundles).
https://docstore.mik.ua/orelly/unix3/mac/ch05_03.htm

**Comment by falkTX** [comment]
Good question. I am not sure about these things, but -shared usually does not work for OSX, so we got to use something else.
LADSPA, DSSI, LV2 and a few others are not actual bundles, but real dynamic libraries.
The naming here is a bit off, but it might be we want to make "bundles" indeed.
I can do some reading later on, but if you find something that works well, feel free to change it.

**Comment by jpcima** [comment]
I picked a freeware VST at random to check what is common practice on it, and this one was created as bundle, not dynamic library.
```
Synth1.vst/Contents/MacOS/Synth1: [...] x86_64:Mach-O 64-bit x86_64 bundle [...]
```

I think, `bundle` and `dynamiclib` are interchangeable when it comes to plugins.

This sentence off the document best sums up the difference: "You cannot link directly against a bundle. Instead, bundles must be dynamically loaded and unloaded by the dyld APIs."

Following a patch however, my VST with UI have an anomaly in Carla, they crash when removed.

**Comment by jpcima** [comment]
From further study, it was revealed that dylib have a loader directive known as `LC_ID_DYLIB` which encodes the library name into the binary (whatever is passed as -o), and it's a normal thing.

It's displayed indifferently at the head in the `otool -L` output, but it's not a link.
It confused the `macdylibbundler`, however it was a defect of the tool itself.

Therefore, described behavior is not a bug.

It seems to remain, however, that "bundle" is common practice for plugins, in audio and general.
In the linked article, the following is read:
>It is important to point out that shared libraries cannot be unloaded.

If "shared libraries" do not unload, may it explain why only bundles are crashing Carla? (no cleaning up = no crash at close?)

**Comment by falkTX** [comment]
Very interesting. It might be nice to always use `-bundle` in DPF anyway, as it matches what we try to do.
