### ISSUE TITLE
Unable to build release 2.0.0. Directory dpf empty

### ISSUE THREAD

**Issue by porcupineofthemoon** [DISTRHO/DPF#205]
After download the tarball or zip-file, unpacking and running make the build fails with the message that
dpf/Makefile.base.mk is not found. 
Having a closer look the full directory is empty.

**Comment by falkTX** [comment]
What are you referring to exactly? Did you download a plugin source and try to build it?
The DPF project itself has no releases..

**Comment by porcupineofthemoon** [comment]
Sorry. For the bad description. Yes I was trying to download the plugin source code version 2.0.0 from the releases page and building it. The Makefile is trying to include dpf/Makefile.base.mk. This file does not exist in the tarball.

**Comment by falkTX** [comment]
Which plugin?

In any case, premade GitHub tarballs do not include git submodules so this is why you do not see the dpf folder contents there.
You can download DPF separately and place it there, or clone via `git --recursive` which will work fine

**Comment by porcupineofthemoon** [comment]
Dragonfly-reverb-2.0.0. The source code tar.gz from here https://github.com/michaelwillis/dragonfly-reverb/releases. I will try to clone via git instead.

**Comment by michaelwillis** [comment]
@porcupineofthemoon The dragonfly reverb repo uses a git submodule to include DPF. When first cloning the repo, use the `--recurse-submodules` command line option.

**Comment by porcupineofthemoon** [comment]
I can confirm that cloning using git and building the source code works. Although, it would be great, if the tar.gz or zip-archives contain all necessary files to actually build the source code without having to download extra files from git. 

Further, I wanted to say thanks a lot for your great contribution to linux audio. I wrote a simple ebuild to install it on gentoo machines: [https://bugs.gentoo.org/701180](https://bugs.gentoo.org/701180)

**Comment by michaelwillis** [comment]
@porcupineofthemoon Oh right, Github automatically generates the source package without the submodule. I wish it would include it, but I do have the full source packaged as DragonflyReverb-Source-v2.0.0.tar.gz from the release page.

**Comment by falkTX** [comment]
GitHub is at fault here. we cannot disable the automatic tarballs on release...
