### ISSUE TITLE
OpenGL deprecated in macOS

### ISSUE THREAD

**Issue by michaelwillis** [DISTRHO/DPF#206]
Building my DPF project on MacOS results in several warnings like this:

```
src/Geometry.cpp:449:5: warning: 'glBegin' is deprecated: first deprecated in macOS 10.14 - OpenGL API deprecated. (Define GL_SILENCE_DEPRECATION to silence these warnings) [-Wdeprecated-declarations]
    glBegin(GL_LINES);
```

Does DPF have any plans to accommodate the fact that MacOS may completely stop supporting OpenGL? I'm disappointed by Apple's decisions, but I would really like to continue releasing plugins that can be used on MacOS.

**Comment by falkTX** [comment]
There is no such plans at the moment, though if a change happens would be to go to vulkan.
macOS now only officially supports apple proprietary APIs (Metal), which means a cross-platform graphics framework no longer exists.
OpenGL and Vulkan are the closest we have. if Apple really removes all OpenGL support, we either find a way to convert the calls into Metal, or drop support for macOS.

There is no way around this, Metal is macOS/iOS specific and will not work on other systems.

Safest bet for now is to draw the UI using DPF provided methods, either the OpenGL ones or nanovg stuff.
Cairo is also an option, though it removes the simplicity of using OpenGL (no need to build anything extra like cairo)

**Comment by michaelwillis** [comment]
Understood. I'm hoping that it is mostly bluster, since "deprecated" can mean unofficial support for many year. However, it can also mean that support is completely dropped on any given release, which makes me nervous.
