### ISSUE TITLE
LV2 parameter offset incorrect

### ISSUE THREAD

**Issue by jpcima** [DISTRHO/DPF#209]
Hi, If I create a plugin which has MIDI In and I forget to set it's a synth, LV2 parameter offset is incorrect.

Below is a configuration which fails.
Since it has 2 Audio ports and 1 MIDI, Parameter offset is supposed to be 3, but I get 2.

```
#define DISTRHO_PLUGIN_IS_RT_SAFE 1
#define DISTRHO_PLUGIN_NUM_INPUTS 0
#define DISTRHO_PLUGIN_NUM_OUTPUTS 2
#define DISTRHO_PLUGIN_WANT_TIMEPOS 0
#define DISTRHO_PLUGIN_WANT_PROGRAMS 1
#define DISTRHO_PLUGIN_WANT_MIDI_INPUT 1
#define DISTRHO_PLUGIN_WANT_MIDI_OUTPUT 0
```

**Comment by falkTX** [comment]
This was fixed in https://github.com/DISTRHO/DPF/commit/23db12f290be2fcafddc9468bcad7ca18f5e12bc
Forgot to close this ticket.
