### ISSUE TITLE
UI not rendering (black window) on laptop, works on desktop

### ISSUE THREAD

**Issue by rghvdberg** [DISTRHO/DPF#21]
I've compiled the plugin-examples and the UI with text labels (Info plugin) doesn't show anything but a black window on my laptop 
Kubuntu 17.04 intel onboard gfx card

On the desktop pc (nvidia gfx card) everything works fine.
Mint 18 (== Ubuntu 16.04)

**Comment by falkTX** [comment]
Please try the MVerb plugin.
Text display requires OpenGL 2.0, while normal bitmaps only needs OpenGL 1.1.
MVerb uses both bitmaps and text, it's a good plugin to test these things.

Link https://github.com/DISTRHO/MVerb (don't forget the submodules before building)

To see if it's an issue with graphics drivers, you can use this:
```
export LIBGL_ALWAYS_SOFTWARE=1
/path/to/MVerb
```

**Comment by rghvdberg** [comment]
found it !
`fFont = createFontFromFile("sans", "/usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf");`

I don't have that font installed on the laptop .. **facepalm**

I'm closing this issue :-)

**Comment by falkTX** [comment]
dpf has a font included that you can use freely.
see mverb code on how to access it.

**Comment by rghvdberg** [comment]
Found it :-)
