### ISSUE TITLE
Building on raspberry pi

### ISSUE THREAD

**Issue by alignwaivers** [DISTRHO/DPF#211]
I was simply trying to build some of the examples on the raspberry pi (4 b) but failed 
![image](https://user-images.githubusercontent.com/26056586/71962507-6feb8d00-31ae-11ea-8689-f15ffbb23305.png)

Sorry, I know the target here is not me who is not a C++ dev but I'm trying to learn and test out the examples, and I went to the [documentation](https://distrho.github.io/DPF/) which was even more confusing to me. What am I doing wrong? Any insights appreciated, thanks much!

**Comment by falkTX** [comment]
This should not be happening if you build from latest git.
Which commit hash is this? or did you download a tagged release?

**Comment by falkTX** [comment]
actually no, my bad. a previous commit regarding generic builds was incomplete. I will fix this now.

**Comment by falkTX** [comment]
Fixed in de8ace2f3057fc033ee0477be9d524d3a344cd85

**Comment by alignwaivers** [comment]
Thanks so much as always @falkTX, much appreciated

**Comment by alignwaivers** [comment]
Sadly, I'm not sure how to instantiate any of the plugins or get the examples working from there. Do you have any resources to point to? I don't want to ask you for detailed instructions, but I'm not sure what the next steps would be

**Comment by falkTX** [comment]
Do you mean on how to load them, or how to create your own?

The example build stuff inside the bin/ directory.
You can place the *.lv2 bundles into the yours ~/.lv2/ folder, and starting up any host that supports lv2 will then make them see these plugins
Same can be done with vsts in ~/.vst/ althogh most vst hosts allow you to add a custom path, so you just need to tell that host/daw to also find vst plugins there.

If you want to make your own plugin, best thing is to modify one of the examples, at least initially.
There is WIP developer docs at https://distrho.github.io/DPF/
