### ISSUE TITLE
Widget::setVisible(false) doesn't hide widget

### ISSUE THREAD

**Issue by ryukau** [DISTRHO/DPF#216]
Hi.

As title says, calling `Widget::setVisible(false)` doesn't hide the widget in next draw call. Is this intended behavior?

I'm using `NanoWidget` with `DISTRHO_UI_USE_NANOVG` set to 1.

When I changed `dgl/src/Window.cpp` as following, it starts hiding the widget according to `isVisible()`.

```cpp
void onPuglDisplay() // Line 919.
{
    fSelf->onDisplayBefore();

    FOR_EACH_WIDGET(it)
    {
        Widget* const widget(*it);
        if (widget->isVisible()) // Added visibility check.
            widget->pData->display(fWidth, fHeight, fAutoScaling, false);
    }

    fSelf->onDisplayAfter();
}
```

**Comment by ryukau** [comment]
Sorry, above code was wrong. It didn't hide widget.

Changing `dgl/src/NanoVG.cpp` as following hides `NanoWidget` according to `isVisible()`.

```cpp
void NanoWidget::onDisplay() // Line 976.
{
    NanoVG::beginFrame(getWidth(), getHeight());
    onNanoDisplay();

    for (std::vector<NanoWidget*>::iterator it = nData->subWidgets.begin(); it != nData->subWidgets.end(); ++it)
    {
        NanoWidget* const widget(*it);
        if (widget->isVisible()) // Added visibility check.
            widget->onNanoDisplay();
    }

    NanoVG::endFrame();
}
```

**Comment by falkTX** [comment]
nanovg subwidgets in DPF have some small issues that I still have to fix.
This is one of them, so thanks :)

I need to take care of some JACK related things, but afterwards I will take some time to dedicated to DPF

**Comment by falkTX** [comment]
This has been fixed in the pugl-update-v2 branch, soon to be merged into develop.
