### ISSUE TITLE
support for stencil buffers 

### ISSUE THREAD

**Issue by rghvdberg** [DISTRHO/DPF#217]
according to @ventosus we need GLX_STENCIL_SIZE 
>rgh: do you have a GLX_STENCIL_SIZE somewhere in pugl ? if not, your OpenGl surface won't have support for it

**Comment by ventosus** [comment]
Needs to be added to eh OpenGl attribute lists.

    /** Attributes for double-buffered RGBA. */
    static int attrListDbl[] = {
    	GLX_RGBA,
    	GLX_DOUBLEBUFFER    , True,
    	GLX_RED_SIZE        , 4,
    	GLX_GREEN_SIZE      , 4,
    	GLX_BLUE_SIZE       , 4,
    	GLX_DEPTH_SIZE      , 8,
    	GLX_STENCIL_SIZE    , 8,
    	/* GLX_SAMPLE_BUFFERS  , 1, */
    	/* GLX_SAMPLES         , 4, */
    	None
    };

**Comment by falkTX** [comment]
@ventosus do you know if this has any side effects, or is it safe to set by default?

**Comment by ventosus** [comment]
@falkTX I don't know of any side effects. But my GL foo is limited.

It is set in pugl master [1], that's good enough for me.

[1] https://gitlab.com/lv2/pugl/-/blob/master/pugl/detail/implementation.c#L112

**Comment by falkTX** [comment]
Oh I see.
Since eventually I will update DPF to upstream pugl (just waiting for API to stabilize first before I do any checks), then that is enough for me too.

**Comment by falkTX** [comment]
Pushed to develop branch
