### ISSUE TITLE
Invisible subwidgets can receive mouse interaction

### ISSUE THREAD

**Issue by jpcima** [DISTRHO/DPF#221]
Hi, there is a problem when hiding a group widget, one can still manipulate the subwidgets of the group as if they were not hidden.

Scenario 1:
- create a slider `S`, and make `S` invisible
- mouse cannot manipulate `S` (OK)

Scenario 2:
- create a group `G`, create a slider `S` child of `G`, make `G` invisible
- mouse can manipulate `S`

**Comment by falkTX** [comment]
Fixed in pugl-upstream-v2 branch
