### ISSUE TITLE
VSTi host? 

### ISSUE THREAD

**Issue by MartinBspheroid** [DISTRHO/DPF#224]
Hi there, 
Here's more a question than issue report.
I'm interested in having VSTi acting as host (or "chainer" as people tend to call it). 
Is DPF having such capabilities implemented already or do I have to add them in on top of a standard boilerplate code? 

Cheers
Martin

**Comment by falkTX** [comment]
DPF does not have such a thing, but I have plans to add to my carla plugin host a sorta "plugin-wrapper api" that allows anyone to load any kind of plugin by reusing carla's internals.

**Comment by MartinBspheroid** [comment]
Oh, I see.
I remember referencing Carla for a C++ VST wrapper I made ages ago I made for the Cinder framework. Much water passed under the bridge since then, huh. 
Anyways, I'll give it a go anyways. 
Cheers for a quick response

**Comment by falkTX** [comment]
I was thinking of turning this point into a discussion, but I am just going to close it.
It is not within the scope of DPF to allow hosting of other plugins.

It would be straight forward to do a mini-host based on carla and dpf though, if anyone is willing to work on the UI side for it.
But that would be something that is not this ticket.
