### ISSUE TITLE
Window::isResizable() can return true inside VST2 builds?

### ISSUE THREAD

**Issue by pdesaulniers** [DISTRHO/DPF#225]
If I set `DISTRHO_UI_USER_RESIZABLE 1` inside `DistrhoPluginInfo.h`, then `getParentWindow().isResizable()` always returns true inside the UI, even in VST2 builds. Shouldn't it always return `false` in VST2 builds?

My use case: [Wolf Spectrum](https://github.com/pdesaulniers/wolf-spectrum) has a resize handle in the bottom right corner, and I would like to hide the handle when the window is user-resizable.

**Comment by falkTX** [comment]
Good question... I need to recheck all of this again.
Has to wait a bit right now, currently dealing with the last Carla bug reports and in the process of updating pugl to upstream version.

**Comment by falkTX** [comment]
Fixed on ac93a69edcb04973ddeaede0318055076f397368
VST2 format simply does not allow for such things, it will force that property to be 0.
