### ISSUE TITLE
Don't build Cairo variant of DGL if not needed?

### ISSUE THREAD

**Issue by pdesaulniers** [DISTRHO/DPF#226]
Right now, it seems like my OpenGL + NanoVG plugin has a build dependency on Cairo: https://travis-ci.org/github/pdesaulniers/wolf-spectrum/jobs/685132629#L481-L493

Could there be some way to avoid building the Cairo variant of DGL when it is not used (and vice-versa)? I guess it would be a matter of adding two variables named `BUILD_CAIRO` and `BUILD_OPENGL` and add them to the `ifeq` statements here: https://github.com/DISTRHO/DPF/blob/e1008f463b943ecd23e9584beb5f6cfa054c3e0f/dgl/Makefile#L61-L69

**Comment by pdesaulniers** [comment]
Hum, I've just realized that this should not be an issue if Cairo is not installed to begin with... Still, I suppose we don't have to build the Cairo variant if the UI does not use it.

**Comment by falkTX** [comment]
there is no way to know in advance if any UI in a project uses cairo or not.
you can just pass "HAVE_CAIRO=false" while building dgl, so cairo is assumed not present and thus not built.

**Comment by pdesaulniers** [comment]
OK, right. I had tried
```
	HAVE_CAIRO=false $(MAKE) -C dpf/dgl
```
...but it seems like I had to put the variable on the right:
```
	$(MAKE) -C dpf/dgl HAVE_CAIRO=false
```
Sorry for the noise :/

**Comment by pdesaulniers** [comment]
In case someone is reading what I said above, I think this is the correct approach:
```
$(MAKE) -C dpf/dgl ../build/libdgl-opengl.a
```

This is what Dragonfly Reverb does: https://github.com/michaelwillis/dragonfly-reverb/blob/005038918875827114c2bac9e4d2bf863d112e51/Makefile#L15
