### ISSUE TITLE
Win/Mac standalone?

### ISSUE THREAD

**Issue by vllur** [DISTRHO/DPF#227]
Hello,
is it possible to make standalone binaries for Win and Mac, like the Jack standalone for Linux?
If not, is there a chance that this could be implemented?

**Comment by falkTX** [comment]
you can have the JACK standalone for win/mac ;)

not against doing such things, but before that is possible we would need a way to setup the audio engine. JACK configuration is done once for all clients, but the same is not true for ASIO or others, we have to select soundcard, buffer size etc in the application.

also, before this is done, it would be much more useful to get more plugin formats, like AU and VST3.
I did the JACK standalone mode mostly as a way to easily debug the plugins while developing.

**Comment by vllur** [comment]
Ok, thanks for clarification :)
