### ISSUE TITLE
License & documentation do not draw attention to (L)GPL'd source files

### ISSUE THREAD

**Issue by julianyon** [DISTRHO/DPF#23]
The main `LICENSE` file contains an ISC style license, giving the impression that the framework is suitable for creating non-copyleft plugins. However, the following files contain a GNU GPL or LGPL notice:

`distrho/src/dssi/dssi.h` (LGPL v2.1+)
`distrho/src/dssi/seq_event-compat.h` (LGPL v2.1+)
`distrho/src/ladspa/ladspa.h` (LGPL v2.1+)
`distrho/src/lv2/lv2-midifunctions.h` (LGPL v2+)
`distrho/src/lv2/lv2-miditype.h` (LGPL v2+)
`distrho/src/lv2/atom-helpers.h` (GPL v2+)
`distrho/src/vestige/aeffectx.h` (GPL v2+)
`distrho/src/DistrhoPluginCarla.cpp` (LGPL – version not specified)🟉
`distrho/src/DistrhoPluginJack.cpp` (LGPL – version not specified)🟉

As the files marked 🟉 are credited to @falkTX I'd be willing to assume that he intends the ISC license of this project to take precedence. However, the others are not. Therefore, _the combined work would fall under the GPLv2_ (preferably “or later”), unless all the other authors have granted exceptions for this project. If that is the case, it needs to be clearly mentioned in the source to avoid any confusion.

In addition, two files mention including JUCE code. I don't know what license applies to it because it is not stated:

`distrho/extra/LeakDetector.hpp`
`distrho/extra/ScopedPointer.hpp`

I should add that the plugin examples include a comment stating “For commercial plugins this should return some short copyright information”, which reinforces the idea that non-free code can use the framework.

I discovered this because I remembered that the VeSTige header is GPL'd. I was prepared to remove it and use the official SDK to build (even though its license sucks) but it occurred to me to grep the source tree, just in case. Not everyone is going to do that, so this situation is inviting a (probably unintended) GPL violation. Indeed, as things stand the framework is already in violation. Even if the intention was for the individual files to be ISC licensed while letting the GPL apply to the whole, and not adding a notice to that effect was an unfortunate oversight, copies of the relevant GPL and LGPL text would need to be included for compliance.

**Comment by julianyon** [comment]
Just to be clear, I'm assuming the stuff from JUCE is fine, I'm merely saying that its license needs to be noted explicitly.

**Comment by falkTX** [comment]
I want to get this fixed by next release, some are easy to handle (Carla and Jack DPF stuff is my own code, I will just change their license; some lv2 stuff can be just removed without issues) but I am unsure about the LADSPA/DSSI situation.

for LADSPA and DSSI, we do not link against any libraries, we simply use header definitions. I am not sure how LGPL applies for such things. I am guessing it will be fine, but needs clarification.

for VST2, indeed the vestige header is GPL.
DPF needs to mention somewhere that VST2 support can be done either with official SDK or vestige header, and let the developer/user decide which one to use.

**Comment by falkTX** [comment]
This has been a long time coming, but started to write some details on https://github.com/DISTRHO/DPF/blob/develop/LICENSING.md
Need to recheck which LV2 headers are used, the GPL specific stuff should be deleted to not lead into confusion.

**Comment by falkTX** [comment]
The LV2 GPL files were deleted, and a note added to the new file describing the LADSPA and DSSI situation.
Also a little note on the readme for this, per f94b49f6592d96ab4cdbb02397f0a1ae01d3089e

With this I consider this issue to be fixed.

**Comment by falkTX** [comment]
Oh and the juce stuff is more verbose per ba2c5db4bbdc0da84f81ce745ce7861fb6a3b722
(I went back to the old files and copied over the header text contents)
