### ISSUE TITLE
getSize() on NanoImage allways returns Size(0,0)

### ISSUE THREAD

**Issue by rghvdberg** [DISTRHO/DPF#241]
- create NanoImage with `createImageFromRGBA()` or `createImageFromMemory()`
- `getSize()` returns Size(0,0)

**Comment by falkTX** [comment]
This has been fixed in 92dc4eeddcdbe5b5b2a646652154d222a4483f2a
An example was added in 6ccd50f0a81d482847663f3a4a884f377d629e16 in order to test NanoImage usage.
