### ISSUE TITLE
On Windows, UI window creation can fail if the window class was already registered

### ISSUE THREAD

**Issue by reuk** [DISTRHO/DPF#251]
https://github.com/DISTRHO/DPF/blob/68ca91217df12cfab582cbe51e1f0d449ba25b72/dgl/src/pugl/pugl_win.cpp#L121-L146

If two UI windows from different DLLs are opened at the same time (i.e. within the same second), their window names are likely to clash, as `srand` will be called with the same value for both windows. This means that the window class names will be identical, and the second call to `RegisterClass` will fail.

Also note that in DGL, the return code of `puglCreateWindow` is not checked, and success is always assumed. This means that, in the case of a failure, the `impl` member of `fView` will continue to be written-to, despite `impl` being freed inside `puglCreateWindow`. Writing to a freed address is UB, and is very likely to crash the entire process.

**Comment by falkTX** [comment]
Good point. There is a WIP branch to update to latest pugl, where hopefully this was taken take of, but need to check again.
I will be working on this in February.

**Comment by falkTX** [comment]
Fixed in cbe07278771727abb9dc2108786f08ff687bc48e
