### ISSUE TITLE
Jack version receives parameter edits on the UI thread

### ISSUE THREAD

**Issue by jpcima** [DISTRHO/DPF#266]
On the standalone, when parameters are changed by the editor, they are processed on the DSP via the UI thread.
It's unlike the ordinary plugin behavior, which always processes parameter changes on the DSP thread.

**Comment by falkTX** [comment]
Not exactly, with VST2 the parameter changes will likely happen in the main/GUI thread too, depending on the host.

**Comment by jpcima** [comment]
OK then never mind, thanks
