### ISSUE TITLE
Upstream pugl branch – Backward incompatible changes

### ISSUE THREAD

**Issue by pdesaulniers** [DISTRHO/DPF#267]
Here are a few backward incompatible changes I've noticed when building my plugin with the upstream pugl branch:

- [x] `NanoWidget` has been replaced with `NanoSubWidget`
- [x]  `getParentWindow().addIdleCallback` has been replaced with `getApp().addIdleCallback`
- [x] The `Widget::MouseEvent` struct has been moved to `Events::MouseEvent`; I had to remove the `Widget::` specifier in some parts of my code
- [ ] The `pos` field in `MouseEvent` is now a `Point<double>` instead of a `Point<int>`, and the `button` field is now a `uint` instead of a `int`
- [ ] `Window::onClose` now has a return type of `bool` (instead of `void`)
- [x] Upstream pugl now includes glu by default: https://github.com/DISTRHO/pugl/blob/b0a018a006c5d7d7796074b86c1b69f8671d2d83/include/pugl/gl.h#L38-L47 It seems like we can disable this dependency by setting `-DPUGL_NO_INCLUDE_GLU_H`

**Comment by falkTX** [comment]
As of right now, only 2 of those items remain.

**Comment by falkTX** [comment]
Need some feedback on this, the mouseEvent stuff should now be usable as-is with both old and new DPF.
If you could confirm, would be great!

The onClose change cannot be escaped. It was not being called on plugins anyway, so it is not important.

**Comment by pdesaulniers** [comment]
Here is a reduced test case which would compile on old DPF, but does not compile on new DPF:

```c++
void doSomethingWithPos(const Point<int> &pos) {
    // do interesting stuff with pos here
}

bool UISimpleGain::onMouse(const MouseEvent &ev) {
    doSomethingWithPos(ev.pos);
    return false;
}
```

```
UISimpleGain.cpp: In member function ‘virtual bool DISTRHO::UISimpleGain::onMouse(const DGL::Widget::MouseEvent&)’:
UISimpleGain.cpp:136:27: error: invalid initialization of reference of type ‘const DGL::Point<int>&’ from expression of type ‘const DGL::Point<double>’
  136 |     doSomethingWithPos(ev.pos);
      |                        ~~~^~~
UISimpleGain.cpp:131:43: note: in passing argument 1 of ‘void DISTRHO::doSomethingWithPos(const DGL::Point<int>&)’
  131 | void doSomethingWithPos(const Point<int> &pos) {
      |                         ~~~~~~~~~~~~~~~~~~^~~
```

As for the `button` field, I think it would simply generate some warnings in existing code in some circumstances:

```c++
bool UISimpleGain::onMouse(const MouseEvent &ev) {
    int someButton = 1;

    if (someButton == ev.button) {
        return true;
    }
    
    return false;
}
```

```
UISimpleGain.cpp: In member function ‘virtual bool DISTRHO::UISimpleGain::onMouse(const DGL::Widget::MouseEvent&)’:
UISimpleGain.cpp:134:20: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const uint’ {aka ‘const unsigned int’} [-Wsign-compare]
  134 |     if (someButton == ev.button) {
```

**Comment by falkTX** [comment]
Right, for the first case an easy enough solution is to provide a point-double to point-int automatic conversion.
2nd one is pretty minimal and won't be changed, old dpf was wrong.

**Comment by falkTX** [comment]
ok this is as far as we go regarding backwards compatibility.
the old `master` branch remains untouched and will be kept that way.
move to the new default `main` branch to get new stuff. develop will keep being while new stuff is added for testing, and then things are merged into `main`.
