### ISSUE TITLE
Parameter names not present in VST parameter properties

### ISSUE THREAD

**Issue by yaw-man** [DISTRHO/DPF#286]
A VST host may attempt to retrieve a plugin's parameters' names by looking for a 'label' in the parameter properties, rather than using the parameter name directly.
Currently, DPF does not provide this label, so some hosts (e.g. OpenMPT 1.29) will not display parameter names properly.

**Comment by falkTX** [comment]
This was fixed in 345c971aead2b08c8fe6af91bea25c0acf04d2c3
