### ISSUE TITLE
Legacy definitions in DistrhoUIPrivateData

### ISSUE THREAD

**Issue by jpcima** [DISTRHO/DPF#288]
There remains a use site of unused `DISTRHO_PLUGIN_TARGET_VST`, following the VST3 update in develop branch.

https://github.com/DISTRHO/DPF/blob/a8f912a7d3debd4b01333dee2780412599c08d30/distrho/src/DistrhoUIPrivateData.hpp#L33

**Comment by falkTX** [comment]
Fixed in 97bb090e3b89a863b6657d485a26c105f2667435 thanks
