### ISSUE TITLE
Issue when host is running in low resolution (Windows only)

### ISSUE THREAD

**Issue by lucianoiam** [DISTRHO/DPF#289]
Steps to reproduce (valid for current develop 92f0f97)

1. Compile examples
2. Right click on desktop -> Display Settings -> Scale and Layout -> Change the size of text, apps and other items -> 150% 
3. Start a non-DPI aware host (like Live 10.1.5). It should look a bit blurry due to scaling.
4. Insert d_Parameters VST

Expected result:
- Host window remains unaffected

Actual result:
- Host window breaks

Background: on a small  13" 1080p screen system scaling comes handy; older apps look blurry but that's preferable to having microscopic text.

Looks like loading the plugin forces the host to "convert" into a DPI-aware process with unpredictable results due to pugl calling `SetProcessDPIAware()` [(exact line here)](https://github.com/DISTRHO/pugl/blob/61d0df48224608f8a71c975c7d0ab1233ce5d266/src/win.c#L135 ). Maybe it's a bit of an edge case but it wasn't happening a couple of weeks ago. If I correctly recall on earlier DPF versions the plugin just stayed lo-res (blurry) following the parent process configuration.

Probably that call should be issued only when running standalone and skip it for plugins?. Now I think any call that may have an effect on the process should be omitted when running as plugin.

Note on the attachment: it was shot via Remote Desktop but that does not affect the experiment, using a physical display leads to the same result.

https://user-images.githubusercontent.com/930494/122043938-345de500-cddc-11eb-83d8-b9e0d0548058.mov

**Comment by falkTX** [comment]
very interesting, I was not aware this could even happen!
I will report the issue upstream.

**Comment by falkTX** [comment]
Older versions of DPF used a very old pugl. As of last month I updated to latest upstream.

Can you confirm that removing `SetProcessDPIAware` fixes this issue?

**Comment by lucianoiam** [comment]
Makes sense. Yes, removing `SetProcessDPIAware` fixes the issue.

**Comment by falkTX** [comment]
Now fixed, patch submitted upstream at https://github.com/lv2/pugl/pull/55
