### ISSUE TITLE
Wrong dimensions reported to REAPER/Mac

### ISSUE THREAD

**Issue by lucianoiam** [DISTRHO/DPF#291]
Looks like a bug and only happens on Mac. Repeating the same for Linux & Win results in REAPER tightly wrapping the plugin UI.

DPF 92f0f97

<img width="1436" alt="Screen Shot 2021-06-17 at 13 59 16" src="https://user-images.githubusercontent.com/930494/122393824-956cf080-cf75-11eb-8c3c-2bcd1ca9c75f.png">

![Screenshot_2021-06-17_14-15-21](https://user-images.githubusercontent.com/930494/122394729-96525200-cf76-11eb-9adb-f44514a3a794.png)

<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/930494/122396007-d82fc800-cf77-11eb-9d87-1a73ce735671.PNG">

**Comment by falkTX** [comment]
is this because of high-dpi use on mac?

**Comment by lucianoiam** [comment]
Likely yes, the Mac has a HiDPI resolution set.

**Comment by lucianoiam** [comment]
The Windows in the screenshot has system scaling set to 150%, btw

**Comment by falkTX** [comment]
Got it. I have it in the plans to investigate macOS and high-dpi in general.
Dont have a retina display, but have a 4k tv that can simulate it.

For standalones, DPF needs to be able to find the scale factor in use too.
Shouldn't be too difficult on macOS and Windows, biggest pain is on Linux trying to detect scale factor in the many DEs available..

**Comment by lucianoiam** [comment]
The dpf-webui project has a `platform::getSystemDisplayScaleFactor()` function that also works standalone, but I'd really like to switch to DPF's own methods when ready ( assuming there's some WIP there )

**Comment by lucianoiam** [comment]
I believe there is a coordinate space mismatch between DGL and what REAPER expects. Likely the former is including the screen scaling factor in its math, and the latter expects unscaled NSView frame values. Sorry I cannot submit a patch this probably requires non-trivial changes. A workaround is unapplying the scale factor here:

DistrhoUI.cpp

```
void UI::onResize(const ResizeEvent& ev)
{
    UIWidget::onResize(ev);

    const uint width = ev.size.getWidth() / theCurrentScaleFactor; 
    const uint height = ev.size.getHeight() / theCurrentScaleFactor;
    uiData->setSizeCallback(width, height);
}
#endif // !DISTRHO_PLUGIN_HAS_EXTERNAL_UI
```

**Comment by lucianoiam** [comment]
This has been working for a while now.
