### ISSUE TITLE
Wrong initial window size for LV2

### ISSUE THREAD

**Issue by lucianoiam** [DISTRHO/DPF#294]
I believe this is a bug because VST version of the same plugin starts with the expected size, so do unrelated LV2 plugins on Carla.

DPF c0ad83e
 
![Screenshot_2021-06-29_00-43-07](https://user-images.githubusercontent.com/930494/123713057-dddcb600-d873-11eb-80d4-3055ea1a77aa.png)

**Comment by falkTX** [comment]
This is not a bug but expected.
The use of lv2 ui resize extensions was a mistake, and we (lv2 devs) are trying to move away from it.
See https://github.com/lv2/pugl/issues/42 for a little more discussion.

If you use carla from git, this will work.
Or wait for 2.3.1 which I will release in a couple of days.

I am trying to lead the way for LV2 plugin UIs to work in terms of size without extensions. It is going to take a little while until everything works 100%, but at least Carla and DPF side are ready now.
(Carla likely will have issues on macOS and Windows, not sure, need to test resizing on those platforms)

**Comment by lucianoiam** [comment]
That is right, just built latest source it works as expected ( should have tried first in fact ... )

Thanks for sharing the link, interesting discussion.  I'll close the issue now since it does not apply to Carla.git
