### ISSUE TITLE
Plugin does not get keyboard input under some circumstances

### ISSUE THREAD

**Issue by lucianoiam** [DISTRHO/DPF#296]
This is reproducible on REAPER/Mac at least. The culprit seems to lie on some unfinished code, these methods are actually being called but are no-ops :

https://github.com/DISTRHO/DPF/blob/b1683bebbcd7feac04d3124982c4c34bb42a26c6/distrho/src/DistrhoUIInternal.hpp#L319

https://github.com/DISTRHO/DPF/blob/b1683bebbcd7feac04d3124982c4c34bb42a26c6/distrho/src/DistrhoUIInternal.hpp#L327

What is the pending work here? maybe I can help

<img width="1160" alt="Screen Shot 2021-07-03 at 16 33 15" src="https://user-images.githubusercontent.com/930494/124357709-4a153c00-dc1d-11eb-8f22-d53f63b9c2f6.png">

**Comment by falkTX** [comment]
Right, this is some pending work.
I want to not have dedicated methods for plugin-format-side keyboard input.

The best here would be to create the keyboard or special event, and send it to the UI instance.
"timestamp" of the event will be zero.

**Comment by falkTX** [comment]
Did you start any work on this? I am on macOS testing a few things, can quickly fix this up.

**Comment by lucianoiam** [comment]
Not really. That would be great surely you can fix that faster.
