### ISSUE TITLE
licence conflict

### ISSUE THREAD

**Issue by trebmuh** [DISTRHO/DPF#3]
Hi falkx,
Licence of DPF/dgl/src/resources/blender_icons.svg (inside the file itself) mention that :"This content is under CC Attribution-NonCommercial ShareAlike licence 3.0 as long as it's used for Blender 3D GUI. Any other uses are not allowed." but the file "LICENSE-blender_icons.svg.txt" says it's GPL2.

Certainly a boring licensing stuff but I thought you might want to know about this.

**Comment by falkTX** [comment]
I think that's fine.
GPL doesn't really apply to artwork so a CC license is inside the svg file.
The text file references the license for usage in code.

That's how I understand it anyway.

**Comment by trebmuh** [comment]
Thanks for your answer.
Anyway, before you answered, I've been making a package after removing this file and the .png one as well. It doesn't look to affect anything on the GUI.
I've been testing the stand alone version:
![mverb-standalone](https://cloud.githubusercontent.com/assets/8705846/11446756/ed8150ba-953b-11e5-8bb0-fdb489ec5aea.png)
The LADSPA and the LV2 version in Ardour (4.4):
![mverb-ardour-ladspa](https://cloud.githubusercontent.com/assets/8705846/11446762/fd5dbe42-953b-11e5-8a9d-d3de9c3538f1.png)
![mverb-ardour-lv2](https://cloud.githubusercontent.com/assets/8705846/11446763/fd646bd4-953b-11e5-8a15-1beb40e86446.png)
And the LADSPA, VST, DSSI and LV2 version in qtractor:
![mverb-qtractor-ladspa](https://cloud.githubusercontent.com/assets/8705846/11446768/15dac708-953c-11e5-9e2f-e16933bb2503.png)
![mverb-qtractor-vst](https://cloud.githubusercontent.com/assets/8705846/11446770/18fbdb5c-953c-11e5-82ee-73de1986df4c.png)
![mverb-qtractor-dssi](https://cloud.githubusercontent.com/assets/8705846/11446772/1bebb7b0-953c-11e5-839f-55a17a5d94de.png)
![mverb-qtractor-lv2](https://cloud.githubusercontent.com/assets/8705846/11446773/1d5ee90a-953c-11e5-9df1-34d95d9b3795.png)

Everything looks fine and working as expected.
I'm closing the issue then.

**Comment by falkTX** [comment]
the png is already converted to binary.
even if you delete the file, the code for it is still going to be embedded in the final build.

this file includes the declaration of the png: https://github.com/DISTRHO/DPF/blob/master/dgl/src/Resources.hpp
and the cpp version of that includes the actual png data.

**Comment by trebmuh** [comment]
Thanks @falkTX, after a few months without looking into this, I does work perfeclty with your help (and a careful removal inside a few different files).

**Comment by falkTX** [comment]
FYI the GPL related files are no longer included.
My plan with DPF is to make it as free as possible, the GPL stuff is a bit much.
So now DPF is full MIT/ISC licensed again.
(dejavu font is pre-included, but that has a very liberal license too)
