### ISSUE TITLE
System hang when using any DPF-based plugin with Helm synth on Ardour 5

### ISSUE THREAD

**Issue by AS383** [DISTRHO/DPF#30]
I try to process [Helm](http://tytel.org/helm/) synth output with ZamTube and 3BandEq on Ardour 5.12. In both cases ROSA Linux R10 hangs. Also I have [KDE Plasma 5](http://manual.ardour.org/ardour-configuration/system-specific-setup/kde-plasma-5/) specific configuration to keep plugins windows on top.
![distrho_helm_system hang](https://user-images.githubusercontent.com/19341856/35189393-2b19e0da-fe7c-11e7-9d6c-28b1010bf51e.jpg)

**Comment by falkTX** [comment]
Is it only helm that freezes the system, or any juce based plugin? (like tal noisemaker)
are you running a realtime kernel?

**Comment by AS383** [comment]
> Is it only helm that freezes the system, or any juce based plugin? (like tal noisemaker)

I cannot reproduce it with TAL NoiseMaker, but the Helm crashes after I insert it and hit some keys.

> are you running a realtime kernel?

No. The kernel is standard. This is reported by uname: 4.9.60-nrj-desktop-1rosa-x86_64. You can learn more about ROSA kernel on [wiki](http://wiki.rosalab.ru/en/index.php/Kernel).

**Comment by falkTX** [comment]
I forgot to ask the most important thing.. which version of helm and dpf-plugins do you have? how did you install them?
Perhaps I will be able to reproduce this bug if I get this information.

**Comment by AS383** [comment]
I cannot remember a version. Also I change a hardware and cannot reproduce the bug now.
