### ISSUE TITLE
[REQ] Set license on GH

### ISSUE THREAD

**Issue by forart** [DISTRHO/DPF#305]
Hi there, this project is awesome !

Since we've collected it in our [HyMPS project list](https://github.com/forart/HyMPS) (in the [AudioLIBs section](https://github.com/forart/HyMPS/blob/main/AudioLIBs.md)), can you please set licensing terms on this git ?

Thanks in advance !

**Comment by falkTX** [comment]
What part of https://github.com/DISTRHO/DPF/blob/master/LICENSE is not clear?

**Comment by forart** [comment]
1st of all thanks for the fast response.

My "problem" is that not generates the label: https://flat.badgen.net/github/license/DISTRHO/DPF?label=LICENSE

![](https://flat.badgen.net/github/license/DISTRHO/DPF?label=LICENSE)

...it's a non-OSI (aka non-standard) license ?

**Comment by falkTX** [comment]
This is a 100% valid ISC license, it is GitHub just being dumb.
It does not like that the author's name is mentioned at the top of the license :facepalm: 

I imported the changes made to the LICENSE file from develop into master branch, which goes well now with GitHub silly filters.

**Comment by forart** [comment]
Great, thanks !
