### ISSUE TITLE
Add scale factor awareness on Linux

### ISSUE THREAD

**Issue by lucianoiam** [DISTRHO/DPF#308]
I have the following code, what's the best place in the DPF codebase in order to create a PR?

Reference material:

https://wiki.archlinux.org/title/HiDPI
https://ricostacruz.com/til/fractional-scaling-on-xorg-linux

Both links also mention `GDK_SCALE` but just like mentioned in one of them I haven't had success with it. For example gnome-calculator ignores it and follows `GDK_DPI_SCALE` instead.

Also included code for Mac/Win though not sure these are needed.

```C++
float platform::getDisplayScaleFactor(uintptr_t)
{
    const char *dpi;
    float k;

    // Try reading a GTK environment variable

    dpi = getenv("GDK_DPI_SCALE");

    if ((dpi != 0) && (sscanf(dpi, "%f", &k) == 1)) {
        return k;
    }

    // Try reading a Qt environment variable

    dpi = getenv("QT_AUTO_SCREEN_SCALE_FACTOR");

    if ((dpi != 0) && (sscanf(dpi, "%f", &k) == 1) && (k == 0)) {
        dpi = getenv("QT_SCALE_FACTOR");

        if ((dpi != 0) && (sscanf(dpi, "%f", &k) == 1)) {
            return k;
        }
    }

    // Try reading Xft.dpi from .Xresources

    Display* display = XOpenDisplay(0);

    if (display != 0) {
        XrmInitialize();
        char *res = XResourceManagerString(display);

        if (res != 0) {
            XrmDatabase db = XrmGetStringDatabase(res);

            if (db != 0) {
                char* type;
                XrmValue ret;

                XrmGetResource(db, "Xft.dpi", "String", &type, &ret); 

                if ((ret.addr != 0) && (strncmp("String", type, 64) == 0)) {
                    if (sscanf(ret.addr, "%f", &k) == 1) {
                        return k / 96.f;
                    }
                }
            }
        }

        XCloseDisplay(display);
    }

    return 1.f;
}
```

It is easier on Mac and Windows and doable on a plugin window-basis :

```C++
float platform::getDisplayScaleFactor(uintptr_t window)
{
    NSWindow *w;

    // DGL::Window::getNativeWindowHandle() returns NSView* instead of NSWindow*

    if ([(id)window isKindOfClass:[NSView class]]) {
        w = [(NSView *)window window];
    } else {
        w = (NSWindow *)window;
    }

    return (w.screen ? w.screen : [NSScreen mainScreen]).backingScaleFactor;
}
```

```C++
float platform::getDisplayScaleFactor(uintptr_t window)
{
    float k = 1.f;
    PROCESS_DPI_AWARENESS dpiAware;

    if (SUCCEEDED(stub::GetProcessDpiAwareness(0, &dpiAware))) {
        if (dpiAware != PROCESS_DPI_UNAWARE) {
            HMONITOR hMon = MonitorFromWindow((HWND)window, MONITOR_DEFAULTTOPRIMARY);
            DEVICE_SCALE_FACTOR scaleFactor = DEVICE_SCALE_FACTOR_INVALID;

            if (SUCCEEDED(stub::GetScaleFactorForMonitor(hMon, &scaleFactor))) {
                if (scaleFactor != DEVICE_SCALE_FACTOR_INVALID) {
                    k = static_cast<float>(scaleFactor) / 100.f;
                }
            }
        } else {
            // Process is not DPI-aware, do not scale
        }
    }

    return k;
}
```

**Comment by falkTX** [comment]
Thanks!

Some comments:
- the macOS case should already be handled fine in the current code.
- qt env var QT_AUTO_SCREEN_SCALE_FACTOR doesnt work the way you expect. when QT_AUTO_SCREEN_SCALE_FACTOR is set to 1, qt will just try to guess scale factor (compared to something else it does by default? dont know). setting QT_SCALE_FACTOR will override QT_AUTO_SCREEN_SCALE_FACTOR. so QT_AUTO_SCREEN_SCALE_FACTOR is meaningless here

**Comment by falkTX** [comment]
Something seems wrong with those gdk env vars.
Here is with GDK_SCALE=2

![Screenshot_20210818_143736](https://user-images.githubusercontent.com/1334853/129907985-567e1b47-2a09-4b48-b9fe-c266174e2cd6.png)

And now with GDK_DPI_SCALE=2

![Screenshot_20210818_143811](https://user-images.githubusercontent.com/1334853/129908072-9c6c4274-5950-4c84-b731-cfa300d2d075.png)

So GDK_DPI_SCALE kinda works, but it only seems to scale the text.

**Comment by falkTX** [comment]
Purposefully setting my screen via KDE to 1.5 scaling in order to test this.
As expected, DPF does not detect the scaling:

![Screenshot_20210818_145638](https://user-images.githubusercontent.com/1334853/129911314-9a2437a4-42cc-4b1f-9bb7-d565d3c50d2c.png)

Carla can (notice the more crip looking GUI, also "Frontend pixel ratio is 1.5" printed in the terminal)

![Screenshot_20210818_145733](https://user-images.githubusercontent.com/1334853/129911512-b82af35a-66f7-4f6c-b02c-ef1380ee2c3e.png)

KDE sets up some env vars:
```
$ env | grep QT
QT_ACCESSIBILITY=1
QT_SCREEN_SCALE_FACTORS=DisplayPort-0=1.5;HDMI-A-0=1.5;DVI-D-0=1.5;
QT_EXCLUDE_GENERIC_BEARER=1
QT_AUTO_SCREEN_SCALE_FACTOR=0
```

**Comment by falkTX** [comment]
Added something for this in 49bd6247477570ca197c17dfae1c5076471cc04d
Works here:

![Screenshot_20210818_152651](https://user-images.githubusercontent.com/1334853/129916328-51565460-29c5-463e-bc9b-19e71cb20b3e.png)

Please confirm if it works for you too.

**Comment by lucianoiam** [comment]
Ok on QT_AUTO_SCREEN_SCALE_FACTOR==0 being unnecessary.

> So GDK_DPI_SCALE kinda works, but it only seems to scale the text.

Here on Gnome Shell it does not work (screenshot below). This is from https://wiki.archlinux.org/title/HiDPI:

_Firefox should use the #GDK 3 (GTK 3) settings. However, the suggested GDK_SCALE suggestion does not consistently scale the entirety of Firefox, and does not work for fractional values (e.g., a factor of 158DPI/96DPI = 1.65 for a 1080p 14" laptop). You may want to use GDK_DPI_SCALE instead. Another option, which will avoid Firefox-specific settings in many setups is to use the settings in #X Resources as Firefox should respect the Xft.dpi value defined there._

Not sure that applies only to Firefox or not (and not even sure I am understanding the whole pararaph!)   GDK_DPI_SCALE supports fractional scaling and GDK_SCALE not. Anyways, the calculator is an example of how choppy this is... what if we support both? first check for GDK_SCALE, then for GDK_DPI_SCALE ?

<img width="1301" alt="Screen Shot 2021-08-18 at 16 22 45" src="https://user-images.githubusercontent.com/930494/129916535-fb475039-9c43-442d-a9d8-ab1d0184a814.png">

**Comment by lucianoiam** [comment]
> Added something for this in [49bd624](https://github.com/DISTRHO/DPF/commit/49bd6247477570ca197c17dfae1c5076471cc04d)
> Works here:
> 
> ![Screenshot_20210818_152651](https://user-images.githubusercontent.com/1334853/129916328-51565460-29c5-463e-bc9b-19e71cb20b3e.png)
> 
> Please confirm if it works for you too.

Works great!  maybe it is better to settle on the xrdb method and avoid black magic.

<img width="1301" alt="Screen Shot 2021-08-18 at 16 34 10" src="https://user-images.githubusercontent.com/930494/129917558-8330a934-3d0b-45a7-b9b8-ef3716f0f5fe.png">

**Comment by falkTX** [comment]
> Works great! maybe it is better to settle on the xrdb method and avoid black magic.

You mean to avoid random env vars? If so, I agree 100%.

My guess is that since you are using gnome, it skips the GDK_SCALE and uses a setting from the gnome desktop instead.

**Comment by lucianoiam** [comment]
> > Works great! maybe it is better to settle on the xrdb method and avoid black magic.
> 
> You mean to avoid random env vars? If so, I agree 100%.

Yes. Well the env vars are documented but which vars to pick depends on the UI toolkit and DPF does not enforce any toolkit so xrdb fits better. I think that is the best argument.

> 
> My guess is that since you are using gnome, it skips the GDK_SCALE and uses a setting from the gnome desktop instead.

Makes sense.

I guess this can be closed now. That was fast, thanks!

**Comment by falkTX** [comment]
tbh I didnt expect this to just work. JUCE has not supported high-dpi on Linux for such a long time, really thought it was going to be super tricky.
I am going to request some feedback from the people at mastodon.
We should also verify if this works on XWayland, though I assume it does..

**Comment by lucianoiam** [comment]
It works on XWayland, the screenshot above actually shows a Gnome Shell session on Wayland.

There does not seem to be a one-size-fits-all solution for Linux, I guess Xft.dpi might not be present on some systems that still support HiDPI by some other means like configuring Gnome.

Maybe the JUCE folks decided to ignore the issue on the lack of standardization? who knows.

**Comment by falkTX** [comment]
Since it seems to be working on Gnome and KDE, that covers the bigger portion of users.
Would be interesting to test on MATE/Cinnamon or other stuff that still uses Gtk2.

This is mostly only useful for standalones anyway. LV2, VST2 and VST3 provide ways for the host to report the scaling factor to use. The fallback is good to have in place for hosts that do not report this information, which can be a few on Linux since most opensource devs dont care about high-dpi (not yet anyway).

**Comment by lucianoiam** [comment]
Agreed

**Comment by falkTX** [comment]
Just added Windows support too based on your code idea, as per 4ce7dec3e96b00de05acb29e15939a9c460113e0
Thanks!

Confirmed to work on Wine and real Windows in a VM

![Screenshot_20210819_125548](https://user-images.githubusercontent.com/1334853/130064417-1f8469b1-de84-45c1-9102-ce68679470f2.png)

Didnt get any reports of this feature being broken on Linux, so I think we are good now :)

**Comment by lucianoiam** [comment]
Great to know !!
