### ISSUE TITLE
External UI stays around when closed from the host side

### ISSUE THREAD

**Issue by ventosus** [DISTRHO/DPF#31]
Issue
* The process that the external UI spawns is never killed if the UI is closed via host

Reproduce
* Open Qtractor
* Add ZynAddSubFx plugin
* toggle Plugin Settings->Edit -> opens 1. external UI
* toggle Plugin Settings->Edit -> nothing (should close 1. external UI)
* toggle Plugin Settings->Edit -> opens 2. external UI
* toggle Plugin Settings->Edit -> nothing (should close 2. external UI)

Result
* 2 external UIs stay around, although both should have been closed

Problem
* ExternalWindows::terminateAndWaitforProcess seems not to be called from lv2ui:hide

**Comment by falkTX** [comment]
Which UI type are you using for zyn?

**Comment by ventosus** [comment]
Well, there's only one compiled on ArchLinux, it's a ui:showInterface, aka new external UI.

This is zyn 3.0.3 btw.

`
<http://zynaddsubfx.sourceforge.net#UI>
    lv2:extensionData ui:idleInterface ,
                      ui:showInterface ,
                      <http://kxstudio.sf.net/ns/lv2ext/programs#Interface> ;

    lv2:requiredFeature <http://lv2plug.in/ns/ext/options#options> ,
                        <http://lv2plug.in/ns/ext/urid#map> 
`

**Comment by falkTX** [comment]
I know that.. I'm asking if it's fltk, ntk or zyn-fusion.
Sorry I wasn't clear before.

My guess is that it uses fltk.

**Comment by ventosus** [comment]
Ah you were asking for the toolkit, sorry

It is fltk, indeed

**Comment by falkTX** [comment]
I believe this is now fixed in the `external-ui-tests` branch.
I added an example plugin in order to test this more easily.
Works fine here, would be nice if you could confirm. Thanks!

**Comment by pdesaulniers** [comment]
Yep, seems fixed :)

**Comment by falkTX** [comment]
I was waiting for @ventosus to confirm, since he was the original reporter of the bug.
But seeing the fix in the code directly, I can assume it is really fixed now.
(branch has been merged into develop now)
