### ISSUE TITLE
Forcing a fixed scale factor?

### ISSUE THREAD

**Issue by lucianoiam** [DISTRHO/DPF#311]
This is actually question, is it possible to force a plugin scale factor to be 1x regardless what the host or system are saying?

A Linux plugin I'm working on broke after https://github.com/DISTRHO/DPF/commit/49bd6247477570ca197c17dfae1c5076471cc04d because of the somewhat complex equilibrium between host/plugin scale management and the plugin's webview own scale mgmt. I foun  the only solution to be forcing `puglGetDesktopScaleFactor()` to return 1. That explains why there's a difference after this commit but  that value is actually used by some logic I don't understand. 

I could not come with a general solution on my side because the plugin looks perfect standalone or within Carla, but breaks on REAPER and Bitwig. So instead of thinking about workarounds I thought it could be a better idea to make any scale-related "automatic" feature optional (assuming there is such thing).

**Comment by lucianoiam** [comment]
Found the culprit https://github.com/DISTRHO/DPF/blob/ed1275997091c51c539c75ae00709912f6a044af/distrho/src/DistrhoPluginVST2.cpp#L695

The framework is making a decision when the host doesn't support scale factor, that is the "automatic" mentioned above.

**Comment by falkTX** [comment]
So this is only broken for VST2, not LV2? (in reaper)

**Comment by lucianoiam** [comment]
Well I wouldn't necessarily say it is broken, probably DGL-based plugins are benefited from this, my "complain" is the lack of consistency because if a certain host does not support scaling then the plugin will look different compared to other hosts where scaling is supported. Ensuring consistent size across hosts sounds desirable, in detriment of the automatically improved experience on some hosts.

Let me check LV2

**Comment by falkTX** [comment]
There might be some hosts that do not report the scaling information to the plugin, but still can scale with the desktop (due to being made with frameworks like Qt). The workarounds are in place for such hosts.
But it should not be in detriment of others, let's try to handle as many hosts as possible.

**Comment by falkTX** [comment]
Maybe the division thing is really only needed for macOS?
And we can ignore the check for == 0 since it is always the case there.

**Comment by lucianoiam** [comment]
On Mac and Windows haven't seen issues like this so far. This is a screenshot from REAPER/Linux, Xft.dpi=118, REAPER ui_scale=1.66 and maybe some other config I don't recall. 

Notice how the REAPER viewport looks smaller than standalone, despite the scale factor is the same for both. For LV2 viewport looks correct but scale factor is bigger (1.7 -- not seen in screenshot).

Also tried with the patch above but didn't make a difference for d_info  ( though that works for my own plugin ).

<img width="1108" alt="Screen Shot 2021-08-23 at 22 43 07" src="https://user-images.githubusercontent.com/930494/130518907-735694fd-229f-4bdf-99fd-908b61993145.png">

**Comment by falkTX** [comment]
I suppose the hosts provide the scaling info on windows, but not on linux?
Add a debug print around the VST2 canDo and vendor-specific calls, then we can know for sure.

tbh I didnt investigate this outside carla or macos. if we just make that code block that divides size macos specific, would it resolve the linux issue?
(I am assuming that all hosts you tested pass this scaling info on windows, which from what I seen in juce code would be correct)

**Comment by lucianoiam** [comment]
First I would like to correct something I wrote above:

> Also tried with the patch above but didn't make a difference for d_info ( though that works for my own plugin ).

After retrying the patch DOES fix d_info, in addition to fixing my custom plugin. This makes sense now because visually speaking the issue is exactly the same for both test cases. Guess I was sleepy yesterday.

> I suppose the hosts provide the scaling info on windows, but not on linux?
> Add a debug print around the VST2 canDo and vendor-specific calls, then we can know for sure.

The following only applies to REAPER; they look identical except `hasCockosEmbeddedUI` is missing on Mac.

Linux:

```
effCanDo: hasCockosNoScrollUI
effCanDo: wantsChannelCountNotifications
effCanDo: hasCockosExtensions
effCanDo: hasCockosEmbeddedUI
effCanDo: receiveVstEvents
effCanDo: receiveVstMidiEvent
effCanDo: sendVstEvents
effCanDo: sendVstMidiEvent
effVendorSpecific: index=1936999233, 1179994436
```

macOS:

```
canDo: hasCockosNoScrollUI
canDo: wantsChannelCountNotifications
canDo: hasCockosExtensions
canDo: receiveVstEvents
canDo: receiveVstMidiEvent
canDo: sendVstEvents
canDo: sendVstMidiEvent
effVendorSpecific: 1936999233 1179994436
```

Windows:

```
canDo: hasCockosNoScrollUI
canDo: wantsChannelCountNotifications
canDo: hasCockosExtensions
canDo: hasCockosEmbeddedUI
canDo: receiveVstEvents
canDo: receiveVstMidiEvent
canDo: sendVstEvents
canDo: sendVstMidiEvent
effVendorSpecific: 1936999233 1179994436
```

> 
> tbh I didnt investigate this outside carla or macos. if we just make that code block that divides size macos specific, would it resolve the linux issue?

- Disabling both code blocks (DistrhoPluginVST2.cpp @ 407-408, 695-696) resolves the issue on Linux.
- It is needed on Mac Retina for the recent viewport size fix to work (retried just in case)
- Still need to text on Windows, old version 7 here cannot seem to be able to change the system scale factor (d_info stuck at 1.0)

> (I am assuming that all hosts you tested pass this scaling info on windows, which from what I seen in juce code would be correct)

Only tried on REAPER. I would start by disabling the block for Linux, then properly test Windows and decide. I have a physical Win10 box but no access to it right now.

**Comment by lucianoiam** [comment]
Seems this also needs to be disabled on REAPER/Win10, or in other words leave division enabled only for Mac.

<img width="338" alt="1" src="https://user-images.githubusercontent.com/930494/130651256-2765f789-e3d9-4367-a640-c5f1080d0c80.PNG">

Without / scaleFactor:

<img width="398" alt="2" src="https://user-images.githubusercontent.com/930494/130651281-12a73fbd-e03c-443a-ae93-83cfcb01fdaf.PNG">

Additionally build fails for CairoUI on MinGW, is this something that can be fixed installing some pacman package?

```
Creating JACK standalone for d_cairoui
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lbrotlicommon
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lbrotlidec
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lbrotlicommon
```

**Comment by lucianoiam** [comment]
Btw Carla on Windows does not seem to care about this block, it looks good either way. Does that make sense?

**Comment by falkTX** [comment]
> Seems this also needs to be disabled on REAPER/Win10, or in other words leave division enabled only for Mac.

alright, so division stays on macos only, and we dont even need the check for ==0 since hosts dont send this value.



> Additionally build fails for CairoUI on MinGW, is this something that can be fixed installing some pacman package?

if you are using msys2 or other package manager on windows, well it just doesnt like static builds.
I can add a detection for this as I did for carla, but then these output binaries become useless for redistribution.

**Comment by falkTX** [comment]
> Btw Carla on Windows does not seem to care about this block, it looks good either way. Does that make sense?

carla is sending the scale factor, so it bypassed the ==0 check

**Comment by lucianoiam** [comment]
> carla is sending the scale factor, so it bypassed the ==0 check

I think you already mentioned this, sorry.

> alright, so division stays on macos only, and we dont even need the check for ==0 since hosts dont send this value.

Correct

> if you are using msys2 or other package manager on windows, well it just doesnt like static builds.
> I can add a detection for this as I did for carla, but then these output binaries become useless for redistribution.

Got it. This isn't really serious, caught the error by running make on the DPF root.

**Comment by lucianoiam** [comment]
Fixed in https://github.com/DISTRHO/DPF/commit/8f77ae04f7d6b978b2a6dffd92686d394ce7b9f0
