### ISSUE TITLE
dpf vst3 - pitch is higher than lv2/vst2/jack

### ISSUE THREAD

**Issue by dromer** [DISTRHO/DPF#335]
Seems to be running faster? I create a 500hz sine which matches up in simple scope:

https://i.imgur.com/GiIZIAY.png

Green is the lv2, vst3 is red and clearly at a higher frequency. Seems to be about ~540hz?

**Comment by falkTX** [comment]
I guess the sample rate is not being set correctly, can you verify?

**Comment by dromer** [comment]
How can I see this?

**Comment by falkTX** [comment]
add some prints all around I guess.
the d_info example plugin will show the running sample rate too.

**Comment by dromer** [comment]
Yup, it runs at 44100 unlike the others. It also creates some debug output in the carla log:

```
samplerate is: 44100.000000
dpf_factory::create_instance => 0x7fa280184588 {dpf_tuid_class} {v3_component} 0x7fff49b1deb0
dpf_component::initialize              => 0x4fa3bc0 0x4f496f0
samplerate is: 44100.000000
dpf_component::get_bus_info            => 0x4fa3bc0 0 1 0 0x7fff49b1dce0
dpf_component::terminate               => 0x4fa3bc0
dpf_component::unref                   => 0x4fa3bc0 | refcount is zero, deleting everything now!
dpf_factory::create_instance => 0x7fa280184588 {dpf_tuid_class} {v3_component} 0x4faa708
dpf_component::initialize              => 0x4faa5d0 0x4f496f0
samplerate is: 44100.000000
dpf_component::get_bus_info            => 0x4faa5d0 0 1 0 0x7fff49b1df50
dpf_audio_processor::get_bus_arrangement     => 0x4fa3c58 1 0 0x7fff49b1de80
dpf_component::get_controller_class_id => 0x4faa5d0 (nil)
dpf_edit_controller::initialize                 => 0x4fa3c60 0x4f496f0
dpf_edit_controller::set_component_handler      => 0x4fa3c60 0x4f496f0
dpf_component::get_state               => 0x4faa5d0 0x7fff49b1e000
dpf_edit_controller::set_component_state        => 0x4fa3c60 0x7fff49b1e000
dpf_audio_processor::setup_processing        => 0x4fa3c58
dpf_factory::set_host_context => 0x7fa280184588 0x4f496f0
dpf_component::get_bus_info            => 0x4faa5d0 0 1 0 0x7fff49b1dfd0
dpf_edit_controller::create_view                => 0x4fa3c60 editor
dpf_edit_controller::create_view                => 0x4fa3c60 (null)
dpf_audio_processor::setup_processing        => 0x4fa3c58
dpf_edit_controller::set_component_handler      => 0x4fa3c60 0x4f496f0
dpf_audio_processor::get_bus_arrangement     => 0x4fa3c58 1 0 0x7fff49b1e3a0
JUCE Assertion failure in juce_VST3PluginFormat.cpp:2078
dpf_audio_processor::get_latency_samples     => 0x4fa3c58
dpf_component::set_active              => 0x4faa5d0 1
dpf_audio_processor::set_processing          => 0x4fa3c58 1
```

**Comment by falkTX** [comment]
44.1khz at the start is fine, but it should change dynamically before audio starts processing.
https://github.com/DISTRHO/DPF/blob/cd9434e3d03349f8db45d77938d5095ff61a88a1/distrho/src/DistrhoPluginVST3.cpp#L1072

**Comment by dromer** [comment]
I'm now doing the print in the constructor, any other place better suited for this?
It seems the constructor is called 3 times though, as we see the print statement 3 times.

The others only call it only once.

**Comment by falkTX** [comment]
1 time for plugin info init, 2 times via juce because reasons, dont ask me.

doesnt the sampleRateChanged callback trigger? I would assume it does...

**Comment by dromer** [comment]
Yeah true, I've moved the print to sampleRateChanged and for the vst3 it is triggered and says its 48k.

Still the pitch is definitely higher ..

**Comment by falkTX** [comment]
it sounds like a problem on your side tbh..

**Comment by dromer** [comment]
It's odd that lv2/vst2/jack all run correctly and only the vst3 is running incorrectly, though.

**Comment by falkTX** [comment]
not incorrectly, it is just that with those it is possible to know the sample rate before the plugin is even constructed.
no such thing on vst3.

**Comment by dromer** [comment]
Well, same code running on all 3 and lv2 (red) and vst2 (blue) are 500hz, vst3 isn't: https://i.imgur.com/8K0fk3W.png

Can't explain this atm.

**Comment by falkTX** [comment]
Do you update the engine sample rate on sampleRateChanged callback?
My guess is that this only works if sample-rate remains constant.
If you modify the initial/constructor sample rate to an arbitrary value and then call sampleRateChanged manually, I bet the same issues appear.

**Comment by dromer** [comment]
Hmmm, I have an idea. Another legacy mistake of the old vst2 implementation in hvcc.

It was checking the new samplerate, which maybe in other implementations is done explicitely. In DPF you really only call that method when there is a change, passing in the new samplerate, but the check is retrieving the same samplerate and comparing the two .. thus it never actually creates the new context!

Will remove this superfluous (and erroneous) check, I think it should work then!

**Comment by falkTX** [comment]
the new sample rate is passed as a variable, so just use that haha

**Comment by dromer** [comment]
Yes it was, but it was comparing it to `getSampleRate()` which is obviously the same value ..

I don't need to compare anything here, this method is only called when there is a sample rate change, so I now recreate the context using the passed on samplerate and that's that.
