### ISSUE TITLE
undefined reference to DISTRHO::createPlugin() 

### ISSUE THREAD

**Issue by SeleDreams** [DISTRHO/DPF#339]
Hi, I have been trying to build a plugin using DPF and cmake on Windows (mingw-w64 toolchain) however i've been having issues getting it to work whether i'm using vst2,lv2 or vst3, the compilation always fails with "undefined reference to DISTRHO::createPlugin"

I at first thought it was maybe something I should implement but didn't implement, but the documentation doesn't mention anything about it and only makes me create a class inheriting from plugin and implementing some methods

is there something i'm missing ?

**Comment by falkTX** [comment]
You are missing creating the function ;)

Just look into any of the examples in the repo, it is always defined.

**Comment by SeleDreams** [comment]
> You are missing creating the function ;)
> 
> Just look into any of the examples in the repo, it is always defined.

I see, it's because this isn't mentionned at all inthe documentation
