### ISSUE TITLE
VST parameters back to default after reloading project when plugin uses states

### ISSUE THREAD

**Issue by pdesaulniers** [DISTRHO/DPF#35]
Here's a way to reproduce the issue:

1. Load the VST version of ZamHeadX2, ZamSynth, ZamVerb or ZaMultiComp in Carla
2. Tweak the plugin's parameters
3. Save the project
4. Load the project

The parameters are now back at their default values.

This also happens in Renoise and Bitwig 1.3.15, but not in Ardour.

If "Use Chunks" is not ticked in the plugin's settings in Carla, the parameters are saved / loaded correctly, but the state is lost.

What's happening? :)

**Comment by falkTX** [comment]
The relevant code is here: https://github.com/DISTRHO/DPF/blob/master/distrho/src/DistrhoPluginVST.cpp#L584

And I see what's going on, the parameter data is not being saved after the chunks.
I remember coding support for this... maybe in some other project.. hmm
