### ISSUE TITLE
setParameterValue from UI has no effect

### ISSUE THREAD

**Issue by SeleDreams** [DISTRHO/DPF#354]
This is an issue I noticed while starting to implement an UI to my plugin
here, the UI events properly get called, and the UI gets updates from the plugin, like when the value changes in the plugin through automation for instance, the UI will get updated to reflect the change however the reverse doesn't seem to be the case, updates to the value sent from the UI don't seem to trigger the setParameterValue method from the plugin, the breakpoint on the video is never reached 

I'm using vst3, i dunno if it's a general dpf issues or a vst3 only issue
https://user-images.githubusercontent.com/16335601/147703296-97ee2680-a04d-4050-9243-cc41c2a1f984.mp4

**Comment by SeleDreams** [comment]
I wonder if it is related to this issue https://github.com/DISTRHO/DPF/issues/343

**Comment by falkTX** [comment]
this was broken on the experimental vst3 side until a 1-2 days ago.
so retry with latest and see if it works now or not.

**Comment by SeleDreams** [comment]
> this was broken on the experimental vst3 side until a 1-2 days ago. so retry with latest and see if it works now or not.

I retried on the latest commit and it still doesn't seem to be working, i'm going to test on another daw to see if it's reaper specific

**Comment by SeleDreams** [comment]
Never mind, seems like it's now fixed, it didn't trigger the breakpoint in my new test because i added the breakpoint at runtime, seems like it doesn't like it when i add them later
