### ISSUE TITLE
integration of nanogui ?

### ISSUE THREAD

**Issue by SeleDreams** [DISTRHO/DPF#355]
I noticed that dpf by default bundles nanovg for UI which can be good for basic stuff but is a bit limited, I noticed there's a project under a similar licence named nanogui which uses nanovg but extends a lot its features to make it a full featured UI framework, i feel like it might be a good idea to integrate it to dpf
https://github.com/mitsuba-renderer/nanogui

**Comment by SeleDreams** [comment]
https://github.com/dalerank/nanogui-sdl there's an sdl port that might be easier to integrate since we can pass a gl context to it more easily

**Comment by SeleDreams** [comment]
I'm trying to integrate it by following the imgui example

**Comment by falkTX** [comment]
Sounds like a widget type perfect for https://github.com/DISTRHO/DPF-Widgets

**Comment by SeleDreams** [comment]
> Sounds like a widget type perfect for https://github.com/DISTRHO/DPF-Widgets

after looking into it seems like nanogui hard depends on glfw so to implement it i must make it as an external embedded gui unless glfw gets added as an available backend for the window creation

**Comment by falkTX** [comment]
You can still fake the glfw side, I do it for https://github.com/DISTRHO/Cardinal which the base source uses glfw but ends up with pugl at the end.
Relevant code is at https://github.com/DISTRHO/Cardinal/blob/main/src/CardinalUI.cpp

**Comment by SeleDreams** [comment]
> You can still fake the glfw side, I do it for https://github.com/DISTRHO/Cardinal which the base source uses glfw but ends up with pugl at the end. Relevant code is at https://github.com/DISTRHO/Cardinal/blob/main/src/CardinalUI.cpp

I see, i'll look into it

**Comment by SeleDreams** [comment]
So after looking into it it seems to be harder to do it this way because nanogui already typedefs glfwwindow etc so i couldn't do it without modifying the source code of nanogui directly, i guess one way to do it might be to fork nanogui and make a version replacing all glfw calls by calls for dpf specifically, i don't think it should be too hard

**Comment by falkTX** [comment]
I am going to be harsh here and closing this, leaving a note yet again for https://github.com/DISTRHO/DPF-Widgets that is where such thing belongs.
For DPF I have interest on pushing the event logic around widget handling, but besides nanovg there wont be another official graphics API in this repo
