### ISSUE TITLE
issues with mac builds

### ISSUE THREAD

**Issue by reathance** [DISTRHO/DPF#362]
ableton refuses to load any of the plugins from this bundle
in fl studio kars, mapitchshift, mafreeverb, magigaverb and mabitcrush have no ui at all 
![image](https://user-images.githubusercontent.com/98173345/150653965-3cb57463-3ee1-455e-b2da-90f250e6d8a2.png)

**Comment by falkTX** [comment]
well those plugins dont have a custom gui, they dont need it.
problem is on the hosts for not supporting such plugins then.

**Comment by reathance** [comment]
alright then, got it.
actually, it took me a hot minute to realize but i can still tweak parameters through the "browse parameters tab in fl"
![image](https://user-images.githubusercontent.com/98173345/150671622-53f4885f-00d2-480f-860c-cac9fa742c24.png)

what about ableton live support though? each time i try to load them up they just dont appear on the channel for whatever reason.

**Comment by falkTX** [comment]
It is working for me in FLStudio btw

<img width="548" alt="image" src="https://user-images.githubusercontent.com/1334853/150674179-67a69f12-b9b5-4ef3-9542-361737743b12.png">

For ableton live, I think only the vst3 dont work, didnt investigate yet why.
You are free to debug this yourself too :)
The VST2 versions seem to work as far as I can tell..

**Comment by reathance** [comment]
thank you! actually vst3 versions are the ones that are having problems in both daws, vst2 both have the ui and work with ableton.
