### ISSUE TITLE
MidiThrough example not working on main branch

### ISSUE THREAD

**Issue by todoesverso** [DISTRHO/DPF#363]
The issue itself is broader than the title, but I think it  perfectly reflects the problem.

I have a very simple toy synthesizer I am working on using DPF. I hadn't touch the code for almost a year so I decided to upgrade to the lastest DPF code and it just didn't produce any sound. I didn't do much debugging than noticing that midi events were not reaching my code in the *run* method.
To confirm that,  I compiled the MidiThrough example and it is not working either, but it DOES work on the develop branch. Unfortunatly I dont have the time (or skils) to do a deeper debugging, but I am more than glad to run any test you could suggest me.

**Comment by falkTX** [comment]
develop is the branch to be using at the moment, I just want to get a bit further in the vst3 implementation before merging that to main.

**Comment by todoesverso** [comment]
Fair enough, will stay with develop :). Thanks!
