### ISSUE TITLE
getPluginFormatName() & Co. not available with direct access

### ISSUE THREAD

**Issue by lucianoiam** [DISTRHO/DPF#366]
What is the reason behind skipping the functions in DistrhoUtils.cpp when `DISTRHO_PLUGIN_WANT_DIRECT_ACCESS` is defined?

I removed the check and build works but not sure about the side effects.

I am looking for a way to transfer non-parameter data from the UI to the Plugin and so far it seems the only way to do it is by getting a pointer the Plugin. Unless there is a better way?  there is no `stateChanged()` in the Plugin class.

I think someone mentioned this in the past but not sure... my use case is transferring WASM code generated in a web view to the Plugin side, to create a DSP hot-swap feature.

https://github.com/DISTRHO/DPF/blob/60b9b76b466ad62a9f64f2eb7557a2563bbbf683/distrho/DistrhoUIMain.cpp#L37

**Comment by falkTX** [comment]
We discussed this already. If direct-access is enabled, both DSP and UI will be on the same binary.
Thus both cant include the same cpp file.


> I am looking for a way to transfer non-parameter data from the UI to the Plugin and so far it seems the only way to do it is by getting a pointer the Plugin. Unless there is a better way? there is no `stateChanged()` in the Plugin class.

I might setup something for this soon, depends on how I go into refactoring states.
You can alternatively just use shared memory. Have a look at https://github.com/DISTRHO/OneKnob-Series which does not use direct-access but still has dsp->ui messages (a float fifo for the UI lines)

**Comment by lucianoiam** [comment]
> We discussed this already. If direct-access is enabled, both DSP and UI will be on the same binary. Thus both cant include the same cpp file.

Yeah now I remember, should not open issues this late lol.

> 
> I might setup something for this soon, depends on how I go into refactoring states. You can alternatively just use shared memory. Have a look at https://github.com/DISTRHO/OneKnob-Series which does not use direct-access but still has dsp->ui messages (a float fifo for the UI lines)

There is a neat SharedMemory class in OneKnob, thanks a lot!

**Comment by falkTX** [comment]
> There is a neat SharedMemory class in OneKnob, thanks a lot!

Yeah with some little cleanup and comments I think it could be added to dpf extras, but I am focusing on Cardinal stuff for now and left the OK series on the side.

https://github.com/Tracktion/choc is something worth keeping an eye on for general utilities btw

**Comment by lucianoiam** [comment]
I starred that repo some days ago will have a look. 

Having SharedMemory in DPF would be great, yes.

**Comment by falkTX** [comment]
I am working on this on a new branch, see https://github.com/DISTRHO/DPF/commits/update-state-value
State init will be done with a struct, rather than just passing key and default value. this way we can extend it to support extra things in the future (this part I didnt push yet).
One caveat is that dsp->ui messages from within the run function wont be supported at the start, not sure if that makes a difference for you. For my usecase at hand, running Cardinal on a MOD unit, I do not need that part which makes the overall approach much easier. Also only doing LV2 initially.

**Comment by lucianoiam** [comment]
This is great, just saw `updateStateValue()` in the new branch. So state init would work like the parameters init, right?.

Also not sure I will ever need state updates from the audio thread tbh.

**Comment by falkTX** [comment]
> So state init would work like the parameters init, right?

exactly. it makes more sense than passing random arguments. should have been this from the start, but oh well..
a side effect is that it should make handling states easier to understand.
we set flags to mark state as RO vs RW, host visible or not, dsp vs ui side, etc

**Comment by lucianoiam** [comment]
Sweet!
