### ISSUE TITLE
VST3: Ableton Live recognizes plugins but does not load them

### ISSUE THREAD

**Issue by lucianoiam** [DISTRHO/DPF#372]
I think this was mentioned before in an unrelated closed issue, it deserves its
own as Live is a wildly popular commercial host for plugins.

So far VST3 seems to work on every DAW/OS combination except on this one.
Tested both Mac and Windows versions of Live and both fail in the same way.
Plugins list in the browser, name, maker, etc. are correctly read but dragging
and dropping them results in "nothing", no instance is created, no error.

These messages are printed though, is there any useful hint?

```
dpf_factory::num_classes
query_interface_factory => 0x6000000d5220 {v3_plugin_factory_3} 0x7ff7bfefbd88 | OK
query_interface_factory => 0x6000000d5220 {v3_plugin_factory_2} 0x7ff7bfefbd90 | OK
dpf_factory::get_class_info_utf16 => 0 0x7ff7bfefbf60
unref_factory::unref => 0x6000000d5220 | refcount 2
unref_factory::unref => 0x6000000d5220 | refcount 1
ref_factory::ref => 0x6000000d5220 | refcount 2
dpf_factory::create_instance => 0x6000000d5220 {dpf_tuid_class} {v3_component} 0x7ff7bfefc498
dpf_component() with hostApplication 0x0
query_interface_component => 0x60000009d550 {v3_component} 0x7ff7bfefc238 | OK
dpf_component::unref => 0x60000009d550 | refcount 1
unref_factory::unref => 0x6000000d5220 | refcount 1
query_interface_component => 0x60000009d550 {v3_audio_processor} 0x7ff7bfefc5d8 | OK convert 0x0
dpf_component::initialize => 0x60000009d550 0x60000009d7c0 | hostApplication 0x60000009d7c0
query_interface_component => 0x60000009d550 {v3_audio_processor} 0x7ff7bfefc258 | OK convert 0x600002aa9e30
dpf_component::get_bus_info => 0x60000009d550 V3_AUDIO V3_INPUT 0 0x7ff7bfefc2c0
dpf_audio_processor::get_bus_arrangement => 0x6000033cbe58 V3_INPUT 0 0x7ff7bfefc420
query_interface_component => 0x60000009d550 {v3_audio_processor} 0x7ff7bfefc258 | OK convert 0x600002aa9e30
dpf_component::get_bus_info => 0x60000009d550 V3_AUDIO V3_OUTPUT 0 0x7ff7bfefc2c0
dpf_audio_processor::get_bus_arrangement => 0x6000033cbe58 V3_OUTPUT 0 0x7ff7bfefc420
dpf_audio_processor::setup_processing => 0x6000033cbe58 0x7ff7bfefc5d8
dpf_component::terminate => 0x60000009d550
DPF warning: asked to delete component while audio processor still active (refcount 1)
```

**Comment by MARABOTTO** [comment]
Issue reproduced on Ableton live 10 Suite. Did you find a fix ?

**Comment by falkTX** [comment]
FYI a workaround with latest develop dpf is to set the buses for the audio ports, either stereo or mono.
See https://github.com/DISTRHO/DPF/blob/develop/examples/Meters/ExamplePluginMeters.cpp#L108 as example

This has been verified to work for Cardinal.

I was unable to get a plugin with arbitrary audio ports to load in Live. Maybe it only loads stereo vst3 plugins? Seemed very weird.
The VST3 bus stuff is quite complex IMO, which gets in the way of simpler plugins that do not care about buses at all.

**Comment by lucianoiam** [comment]
First thanks for the hard work on travesty, it is great to have it and so far this is the only issue I could find.

FYI just recompiled the latest examples from develop and Meters still fails to load on Mac Live 10, which declares a stereo bus as far as I understand from the link above.

Also tried with a trial version of Live 11 with no luck.

**Comment by falkTX** [comment]
Huh, very weird, I must be doing something special on the Cardinal side perhaps.
Can you try with the builds from https://github.com/DISTRHO/Cardinal/releases/tag/22.06 ?

I recall having VST3 working with those.

**Comment by lucianoiam** [comment]
The installer copies three plugins, this might provide a hint:

CardinalFx.vst3 -> works
CardinalSynth.vst3 -> works
Cardinal.vst3 -> fails

I'm surprised to see an AU version, was it built with DPF too?

**Comment by falkTX** [comment]
ah so it does work on some cases. so we just need to find what it is doing differently...

AU version is a special sorta hack with dpf inside juce.
https://github.com/DISTRHO/Cardinal/tree/main/jucewrapper has the code for that.

It is not generic enough to be usable for all plugins, plus the whole binary gets quite bloated with juce being thrown in.

**Comment by lucianoiam** [comment]
> ah so it does work on some cases. so we just need to find what it is doing differently...

Summarizing

I confirm setting `port.groupId = kPortGroupStereo` in `initAudioPort()` for the main variant makes Cardinal.vst3 work fine just like the Synth and FX variants.

DPF Meters example already does it but still no VST3.

I've been trying to track this down for a while now but no luck yet.

> 
> AU version is a special sorta hack with dpf inside juce. https://github.com/DISTRHO/Cardinal/tree/main/jucewrapper has the code for that.
> 
> It is not generic enough to be usable for all plugins, plus the whole binary gets quite bloated with juce being thrown in.

That's a nice trick, thanks

**Comment by lucianoiam** [comment]
Adding `#define DISTRHO_PLUGIN_WANT_DIRECT_ACCESS 1` to d_meter's DistrhoPluginInfo.h fixes VST3 on Live. Any idea why that could be only needed for a specific DAW?

**Comment by falkTX** [comment]
oh wow, nice find!

my guess is that Live does not implement certain VST3 things..
when that flag is set to 0, DPF will split the VST3 component and edit controller, which communicate with each other with host messages (similar to how LV2 can do it, but VST3 just has an extra dsp + edit-controller + ui separation)

as you seen, all other hosts can handle, Live is the special one.
I do not want to limit the dsp/ui separation on vst3 though, it is kinda important for DPF, so we will need to see if there is some other way to make it work.

just a wild guess, but maybe the flag to set the vst3 bundle distributable causes issues?

**Comment by lucianoiam** [comment]
I agree on avoiding that flag for making VST3 work, in fact direct access breaks my plugins because they depend on path functions from DistrhoPlugins.cpp .

For the records doing this also breaks VST3 on Live (Carla, Reaper and Bitwig are all fine with 0):

`#define DISTRHO_PLUGIN_NUM_INPUTS 0`
or
`#define DISTRHO_PLUGIN_NUM_OUTPUTS 0`

I commented out two lines in DistrhoPluginVST3.cpp

`// info->class_flags = V3_DISTRIBUTABLE`

And d_meters still does not work, I made sure the codebase was the original (git stash) before applying the above change.

**Comment by falkTX** [comment]
fixed in latest git.
the only dpf based vst3 plugins not possible to load in Live that I see now are those that Live cannot cope with, like pure generators without audio or midi input. metronome is one such plugin, Live does not know what to do with it.
