### ISSUE TITLE
Bad include filename of cairo.h

### ISSUE THREAD

**Issue by jpcima** [DISTRHO/DPF#373]
In various places of dpf, the library is included as `cairo/cairo.h` instead of `cairo.h`.

This seems to creates problems in a vcpkg configuration which uses pkg-config.
I can't be entirely sure, but I suspect that the root `include` of the cairo package in this setup is not part of default -I flags.

If checking `pkg-config cairo --cflags` on Linux, `/usr/include/cairo` is there but `/usr/include` isn't.

There is a log (ctrl-F `fatal error C1083`)
[log.txt](https://github.com/DISTRHO/DPF/files/8492679/log.txt)

**Comment by falkTX** [comment]
we can swap for `cairo.h` then, but issue should be pushed upstream to pugl right?

**Comment by jpcima** [comment]
That is correct. Also I have a successful patched build, which confirms it's as suspected.

**Comment by falkTX** [comment]
Fixed in 3d0d31c5941e3156e9cdcbcfa59655737a1391de
