### ISSUE TITLE
Nested struct weirdness in travesty

### ISSUE THREAD

**Issue by jpcima** [DISTRHO/DPF#374]
In travesty, this sort of pattern is seen sometimes.

```
struct v3_plugin_base {
	struct v3_funknown;
	v3_result (V3_API* initialize)(void* self, struct v3_funknown** context);
};
```

The declaration of the inner struct is without effect on the structure contents.
It hints at the inheritance, which is OK I guess, but has an ill effect as well: it creates an inner struct `v3_plugin_base::v3_funknown` which collides with the top-level `v3_funknown` declaration.

The function pointer `initialize` picks up the inner declaration of `v3_funknown` for its argument, which creates a problem when one tries to interact with the API.

The problem would be resolved by commenting all of the inner structs.

**Comment by falkTX** [comment]
The API is meant to be C-compatible first, then helpers added for C++ compat as needed.
Because of differences between C and C++, that `struct v3_funknown` does the inheritance of methods in C, but nothing in C++.
For now I simply declare C++ friendly versions when needed, such as in https://github.com/DISTRHO/DPF/blob/develop/distrho/src/travesty/audio_processor.h#L244

**Comment by jpcima** [comment]
This means, so these structs get different layout depending from which language they are included?
Surely then, it must be ok to get rid of the struct statement by `#ifndef __cplusplus` directives.

Also for info, I was not using any of these c++ helpers, because of preference the conciseness of c-style struct initializer.
Hence, I was building my v-tables on the basis of these "non-inheriting" structures.

**Comment by falkTX** [comment]
> This means, so these structs get different layout depending from which language they are included?
> Surely then, it must be ok to get rid of the struct statement by `#ifndef __cplusplus` directives.

What do you mean layout changes?
It looks weird for sure and can lead to confusion, plus `v3_funknown` becomes a type on a bunch of other structs.

I have cleaned it up a bit in 48fc694c31f709d4a46f727795917fd3371eb0da

**Comment by jpcima** [comment]
> What do you mean layout changes?

I've pushed the code in progress, that can give you an idea.
https://github.com/jpcima/claptrap/blob/master/sources/v3/v3_component.hpp

**Comment by falkTX** [comment]
I feel like that gets the API in a way that is too similar to the original, something I am purposefully trying to avoid.
Feel free to report issues with the core headers, but I prefer to keep my distance from that clap c++ higher level stuff.

I do know quite a few `v3_cpp_obj` specializations are missing, but most are related to the host side.
Whenever I start implement this in Carla I will add those, but most are not needed for now.
