### ISSUE TITLE
Implementing elements UI as the UI library for DPF

### ISSUE THREAD

**Issue by SeleDreams** [DISTRHO/DPF#376]
I recently ended up discovering the "Elements" UI library, it seems to be a C++ UI library under a non viral license that was from the beginning developped to work well with audio plugin frameworks to compete with JUCE
I feel like this could be a very good thing to integrate it to DPF to make dpf easier to work with.

I am going to personally look into implementing support for it, I think I saw at one point that it had a pugl version somewhere, which should make its implementation easy

**Comment by falkTX** [comment]
same as per #355 use https://github.com/DISTRHO/DPF-Widgets that is where such thing belongs.
For DPF I have interest on pushing the event logic around widget handling, but besides nanovg there wont be another official graphics API in this repo
