### ISSUE TITLE
isHexChar doesn't detect "9"

### ISSUE THREAD

**Issue by markjfisher** [DISTRHO/DPF#378]
I was just perusing the source code changes as I love seeing what's happening in these repos, and noticed this line in DISTRHO/DPF/distrho/extra/FileBrowserDialogImpl.cpp (browse branch):

```c++
static constexpr bool isHexChar(const char c) noexcept
{
    return c >= '0' && c <= 'f' && (c < '9' || (c >= 'A' && c <= 'F') || c >= 'a');
}
```
which will not detect that '9' is a hex character. It should be `c <= '9'`

A quick test:
```c++
int main()
{
    char c = '9';
    bool isHexChar = (c >= '0' && c <= 'f' && (c < '9' || (c >= 'A' && c <= 'F') || c >= 'a'));
    cout << isHexChar;

    return 0;
}
```

**Comment by falkTX** [comment]
Nicely spotted, thanks! I had the inverted logic at some point before committing this code, and ended up not changing one part afterwards.
