### ISSUE TITLE
Support for the CLAP audio plugin standard?

### ISSUE THREAD

**Issue by BillyDM** [DISTRHO/DPF#379]
Does DPF have any plans to support the new CLAP audio plugin standard?

https://github.com/free-audio/clap

**Comment by falkTX** [comment]
No immediate plans, for now focus is going to VST3 as otherwise we would have many WIP formats being worked on.
That said, there seemed to be an offer to sponsor such developments, though I did not look into it at all.

**Comment by dromer** [comment]
See https://github.com/DISTRHO/DPF/issues/383  ;)

**Comment by falkTX** [comment]
CLAP support is official now and has been merged to main branch.
Some tiny details remain, but it is stuff 99% of plugins wont use so current feature-set and implementation is good for making releases. And we already had those with dragonfly-reverb, master_me, ildaeil and cardinal anyway.
I am finishing some final details (unrelated to CLAP) and then will release dpf-plugins collection with clap enabled as well.
