### ISSUE TITLE
VST3 default value not always correct for all parameters

### ISSUE THREAD

**Issue by dromer** [DISTRHO/DPF#385]
As discussed on IRC.

Sometimes the default value of a parameter is not correctly set on the host. Works correctly for VST2 and LV2.

Test plugin that consistently gives the wrong value on the first parameter: https://github.com/dromer/wstd-eq-test
In range `-1, 1` and default set to `0` it's always `-1`.

![](https://i.imgur.com/RJRAqaI.png)

**Comment by falkTX** [comment]
is this fixed with latest develop?
