### ISSUE TITLE
Can Qt-based UI work with DPF?

### ISSUE THREAD

**Issue by AnClark** [DISTRHO/DPF#391]
Hi, falkTX!

I've planned to port Rui no Capella's Vee One Suite to DPF (e.g. SynthV1). The plugin family uses Qt for editor UI.

Even though DPF has its own UI framework (DGL), I still want to adapt their Qt-based UI to DPF directly, since rewriting UI is kind of a tremendous work.

I wonder if there are any possible solutions.

**Comment by falkTX** [comment]
possible, yes. should we? no.

the external ui stuff allows to give control of the window handle to foreign widgets, including embedding as well.
this is how https://github.com/lucianoiam/hiphop works

but because I dont want to contribute to things that are going to generate a LOT of issues, I am not going to explain how to achieve this..
unless you have very very good arguments for it ?

**Comment by AnClark** [comment]
> I dont want to contribute to things that are going to generate a LOT of issues, I am not going to explain how to achieve this..

To begin with, I don't mean DPF should implement Qt support like LV2 UI specification. Just simply make Qt-based UI work together with DPF.

> the external ui stuff allows to give control of the window handle to foreign widgets, including embedding as well.

Luckily, embedded external UI may fit with me.

I used to mistake that "external" means standalone, but actually it refers to UI which is not managed by DHL (e.g. Win32 native window).

I've found [an example in the DOF Repo for reference](https://github.com/DISTRHO/DPF/tree/main/examples/EmbedExternalUI).

Thanks a lot.

**Comment by falkTX** [comment]
Make sure to build Qt as static lib when making use of it for plugin builds.
And be careful on how plugins activate their own QApplication, managing the lifecycle of the global instance is not easy. I recall Qt used to do some things on shutdown that made it not possible to be reactivated/reused again, some freetype cleanup things.

**Comment by AnClark** [comment]
Sorry for late reply due to a bulk of work these days.

It's hard to manage the global instance. Luckily I've got some useful suggestions from other developers, for example, instance counter.

Rui, the author of SynthV1, initializes Qt instance in `lv2_instantiate` descriptor, and destroys in `lv2_cleanup` descriptor. Maybe if I work with DPF, I can do the same stuff in the DSP side during initializing my `Plugin` instance.

---

I already have an Arch Linux package to make sure I can build plugins with static Qt. It requires CMake build system. But seems that the DPF CMake module doesn't support external UI:

https://github.com/DISTRHO/DPF/blob/22413340a6d8ef2ffbf38ce841fb44c448a1a84a/cmake/DPF-plugin.cmake#L78

**Comment by falkTX** [comment]
> Rui, the author of SynthV1, initializes Qt instance in `lv2_instantiate` descriptor, and destroys in `lv2_cleanup` descriptor. Maybe if I work with DPF, I can do the same stuff in the DSP side during initializing my `Plugin` instance.

make sure you can init qt after destroying it, I had issues with this in the past.


> I already have a [Msys2 package](https://github.com/AnClark/msys2-qt6base-static) to make sure I can build plugins with static Qt, on Windows. It requires CMake build system. But seems that the DPF CMake module doesn't support external UI:

correct. the cmake support in dpf has less attention compared to makefiles, mostly because it a contribution. so the supported features are mostly what the initial PR included.
I am open to extend the cmake stuff, see how far you can get it and send a PR/patch even if incomplete. the external-ui example plugin can serve as a test case.

**Comment by AnClark** [comment]
> mostly because it was a contribution. so the supported features are mostly what the initial PR included.
>
> I am open to extend the cmake stuff, see how far you can get it and send a PR/patch even if incomplete. the external-ui example plugin can serve as a test case.

Since SynthV1 is built with CMake only, I can help improving the CMake stuff.

> make sure you can init qt after destroying it, I had issues with this in the past.

I remember that I used to [implement SynthV1 into VST](https://github.com/AnClark/synthv1/tree/vst-implementation/src), via VeSTige. In REAPER for Windows, it was unable to re-initialize: when I unload an instance, and reload, REAPER will crash. Is it the same as what you encountered?

**Comment by AnClark** [comment]
> I remember that I used to [implement SynthV1 into VST](https://github.com/AnClark/synthv1/tree/vst-implementation/src), via VeSTige. In REAPER for Windows, it was unable to re-initialize: when I unload an instance, and reload, REAPER will crash. Is it the same as what you encountered?

I resolved the problem mentioned above: do QApplication instantiation stuff in `effOpen`, and clean-up stuff in `effClose`.

**Comment by AnClark** [comment]
Great, [I've successfully ported synthv1 to DPF](https://github.com/anclark/synthv1/tree/dpf-implementation). Everything works well.

This would be a good example for writing DPF-based plugins with Qt.

**Comment by falkTX** [comment]
This could be something nice for https://github.com/DISTRHO/DPF-Widgets even though it is not the most recommended setup.
Building Qt statically would allow for a better managed plugin experience, and make this actually run on win/mac.

**Comment by AnClark** [comment]
> Building Qt statically would allow for a better managed plugin experience, and make this actually run on win/mac.

I use static Qt on Windows build. It helps a lot when running and distributing the plugins. Here's my Msys2 package config of static Qt 6: <https://github.com/AnClark/msys2-qt6base-static>
