### ISSUE TITLE
DPF fails to build when using Clang?

### ISSUE THREAD

**Issue by pdesaulniers** [DISTRHO/DPF#395]
If I try to compile Wolf Shaper on Arch Linux with the following command:

```
CC=clang CXX=clang++ make
```

...I get the error `unknown argument: '-fno-gnu-unique'`:

```
CC=clang CXX=clang++ make
grep: warning: stray \ before #
make -C dpf/dgl opengl
make[1]: Entering directory '/home/patrick/Code/wolf-shaper/dpf/dgl'
grep: warning: stray \ before #
Compiling src/Application.cpp
clang-14: error: unknown argument: '-fno-gnu-unique'
make[1]: *** [Makefile:181: ../build/dgl/Application.cpp.o] Error 1
make[1]: Leaving directory '/home/patrick/Code/wolf-shaper/dpf/dgl'
make: *** [Makefile:18: libs] Error 2
```

It seems like Clang is not being auto-detected correctly, which causes this branch to be executed: https://github.com/DISTRHO/DPF/blob/22413340a6d8ef2ffbf38ce841fb44c448a1a84a/Makefile.base.mk#L220-L222

On my system, the value of `TARGET_COMPILER` is an empty string.

Any clues? Do I need to pass `CLANG=true` when building the plugin?

**Comment by falkTX** [comment]
This is set in https://github.com/DISTRHO/DPF/blob/main/Makefile.base.mk#L38

It has worked for me in linux gcc, linux mingw, linux clang and macos clang.

What seems to be different for you is makefile, are you running arch or something that would get something super fresh/new?

**Comment by pdesaulniers** [comment]
Yeah, I believe this occurs due to the way `echo` behaves on my system. This line does not return anything:

```
echo '#ifdef __clang__\nclang\n#else\ngcc\n#endif' | clang -E -P -x c - 2>/dev/null
```

I need to use `echo -e` instead:

```
$ echo -e '#ifdef __clang__\nclang\n#else\ngcc\n#endif' | clang -E -P -x c - 2>/dev/null
                                                                                                                
clang 
```

Also, this line emits a warning:

```
$ echo '\#test' | grep -- '\#test'           
grep: warning: stray \ before #                                       
\#test
```

To avoid these issues, would it be ok to use the `printf` command instead of `echo`? AFAIK, the `printf` command should be fairly portable:

```
printf '#ifdef __clang__\nclang\n#else\ngcc\n#endif' | clang -E -P -x c - 2>/dev/null

clang                     
```

**Comment by falkTX** [comment]
echo -e does not work on BSD or macOS, and some windows (cygwin?) things too.
and there is also the case of things being different depending on which makefile version we use.

will try some things later. worst case we call a shell script instead of trying to do everything within the makefile.

**Comment by falkTX** [comment]
I dont know how to reproduce the issue, what system are you using?

**Comment by pdesaulniers** [comment]
I use Arch Linux. I also reproduced the issue on FreeBSD 13.1.

**Comment by AnClark** [comment]
Maybe you can switch to CMake, as CMake will automatically check and filter the build flags.

My plugin can be built on both GCC and Clang on Arch Linux, with CMake.

**Comment by falkTX** [comment]
I forgot I had already solved this for master_me plugin, so imported the same thing that worked there into DPF.
See c7e4ac43f5228cee69b2453d95e56859d7912a50

@pdesaulniers please give it a try, I dont have an archlinux install at hand to test it myself.

**Comment by falkTX** [comment]
needed 1 more little nudge in 34952157be7db5e01c58266431aab253b59f9259

now should really be fixed, final usage being:

```
ifneq ($(shell echo -e escaped-by-default | grep -- '-e escaped-by-default'),-e escaped-by-default)
TARGET_COMPILER = $(shell echo -e '#ifdef __clang__\nclang\n#else\ngcc\n#endif' | $(CC) -E -P -x c - 2>/dev/null)
else ifeq ($(shell echo '\#escaped-by-default' | grep -- '\#escaped-by-default'),\#escaped-by-default)
TARGET_COMPILER = $(shell echo '\#ifdef __clang__\nclang\n\#else\ngcc\n\#endif' | $(CC) -E -P -x c - 2>/dev/null)
else
TARGET_COMPILER = $(shell echo '#ifdef __clang__\nclang\n#else\ngcc\n#endif' | $(CC) -E -P -x c - 2>/dev/null)
endif
```

I tested running 3 different systems at the same time - Ubuntu 20.04, Ubuntu 23.04 and ArchLinux.
They all behave differently!! :rage: 

on the new code, the 1st pass validates only on ArchLinux, the other 2 are equivalent to what I was using before and is known to work on ubuntu, mingw and macOS shells.
so unless one of them triggers the first condition, we should be good.

**Comment by pdesaulniers** [comment]
It appears to work correctly on Arch! Thank you, I'm closing this issue.
