### ISSUE TITLE
LV2 exporter should escape special character

### ISSUE THREAD

**Issue by AnClark** [DISTRHO/DPF#399]
Hi, falkTX!

Some presets names may have special characters like quotation mark (`"`). However, currently LV2 exporter does not escape them, so hosts like REAPER will fail to recognize LV2 plugins.

Here's the line which should be improved:
https://github.com/DISTRHO/DPF/blob/22413340a6d8ef2ffbf38ce841fb44c448a1a84a/distrho/src/DistrhoPluginLV2export.cpp#L326

**Comment by falkTX** [comment]
Fixed in b238d8dc7e5d5a38c54b7a941a71d0fb3cb4be3d thanks!

**Comment by AnClark** [comment]
My pleasure!
