### ISSUE TITLE
Add support for enum parameters

### ISSUE THREAD

**Issue by pdesaulniers** [DISTRHO/DPF#40]
I'm referring to parameters which have a different label for every value.

They seem to be supported by all four plugin formats, except I haven't found an example for DSSI.

**Comment by falkTX** [comment]
LADSPA/DSSI can use LRDF, but it's a waste of time investing into that.

**Comment by SpotlightKid** [comment]
I beg to differ. It makes generated UIs more user-friendly. jalv can interpret LV2 ports of type "enumeration" and Carla should add this too, IMHO.

**Comment by pdesaulniers** [comment]
I believe he was referring to investing time into LADSPA/DSSI features. He does want to implement scale points in DPF :)

**Comment by falkTX** [comment]
now implemented in the develop branch.
See https://github.com/DISTRHO/plugin-examples/blob/e38527d2f6298cea367c1cbbe10a90a10375a553/plugins/Meters/ExamplePluginMeters.cpp#L126 for an example.

Note: implemented on both LV2 and VST.
Not doing LRDF, who cares about ladspa now anyway.
