### ISSUE TITLE
cmake build fails

### ISSUE THREAD

**Issue by rghvdberg** [DISTRHO/DPF#407]
❯ cmake ..
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'cairo'
--   Found cairo, version 1.16.0
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Checking for module 'sdl2'
--   Found sdl2, version 2.0.10
CMake Error at cmake/DPF-plugin.cmake:206 (dpf__target_link_directories):
  dpf__target_link_directories Macro invoked with incorrect arguments for
  macro named: dpf__target_link_directories
Call Stack (most recent call first):
  cmake/DPF-plugin.cmake:155 (dpf__build_jack)
  examples/CairoUI/CMakeLists.txt:4 (dpf_add_plugin)

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Checking for module 'alsa'
--   Found alsa, version 1.2.2
-- Checking for module 'libpulse-simple'
--   Found libpulse-simple, version 13.99.1
CMake Error at cmake/DPF-plugin.cmake:219 (dpf__target_link_directories):
  dpf__target_link_directories Macro invoked with incorrect arguments for
  macro named: dpf__target_link_directories
Call Stack (most recent call first):
  cmake/DPF-plugin.cmake:155 (dpf__build_jack)
  examples/CairoUI/CMakeLists.txt:4 (dpf_add_plugin)

CMake Error at cmake/DPF-plugin.cmake:225 (dpf__target_link_directories):
  dpf__target_link_directories Macro invoked with incorrect arguments for
  macro named: dpf__target_link_directories
Call Stack (most recent call first):
  cmake/DPF-plugin.cmake:155 (dpf__build_jack)
  examples/CairoUI/CMakeLists.txt:4 (dpf_add_plugin)

-- Checking for module 'liblo'
--   Found liblo, version 0.30
CMake Error at cmake/DPF-plugin.cmake:302 (dpf__target_link_directories):
  dpf__target_link_directories Macro invoked with incorrect arguments for
  macro named: dpf__target_link_directories
Call Stack (most recent call first):
  cmake/DPF-plugin.cmake:159 (dpf__build_dssi)
  examples/CairoUI/CMakeLists.txt:4 (dpf_add_plugin)

CMake Error at cmake/DPF-plugin.cmake:206 (dpf__target_link_directories):
  dpf__target_link_directories Macro invoked with incorrect arguments for
  macro named: dpf__target_link_directories
Call Stack (most recent call first):
  cmake/DPF-plugin.cmake:155 (dpf__build_jack)
  examples/FileHandling/CMakeLists.txt:4 (dpf_add_plugin)

CMake Error at cmake/DPF-plugin.cmake:219 (dpf__target_link_directories):
  dpf__target_link_directories Macro invoked with incorrect arguments for
  macro named: dpf__target_link_directories
Call Stack (most recent call first):
  cmake/DPF-plugin.cmake:155 (dpf__build_jack)
  examples/FileHandling/CMakeLists.txt:4 (dpf_add_plugin)

CMake Error at cmake/DPF-plugin.cmake:225 (dpf__target_link_directories):
  dpf__target_link_directories Macro invoked with incorrect arguments for
  macro named: dpf__target_link_directories
Call Stack (most recent call first):
  cmake/DPF-plugin.cmake:155 (dpf__build_jack)
  examples/FileHandling/CMakeLists.txt:4 (dpf_add_plugin)

CMake Error at cmake/DPF-plugin.cmake:206 (dpf__target_link_directories):
  dpf__target_link_directories Macro invoked with incorrect arguments for
  macro named: dpf__target_link_directories
Call Stack (most recent call first):
  cmake/DPF-plugin.cmake:155 (dpf__build_jack)
  examples/Info/CMakeLists.txt:4 (dpf_add_plugin)

CMake Error at cmake/DPF-plugin.cmake:219 (dpf__target_link_directories):
  dpf__target_link_directories Macro invoked with incorrect arguments for
  macro named: dpf__target_link_directories
Call Stack (most recent call first):
  cmake/DPF-plugin.cmake:155 (dpf__build_jack)
  examples/Info/CMakeLists.txt:4 (dpf_add_plugin)

CMake Error at cmake/DPF-plugin.cmake:225 (dpf__target_link_directories):
  dpf__target_link_directories Macro invoked with incorrect arguments for
  macro named: dpf__target_link_directories
Call Stack (most recent call first):
  cmake/DPF-plugin.cmake:155 (dpf__build_jack)
  examples/Info/CMakeLists.txt:4 (dpf_add_plugin)

CMake Error at cmake/DPF-plugin.cmake:206 (dpf__target_link_directories):
  dpf__target_link_directories Macro invoked with incorrect arguments for
  macro named: dpf__target_link_directories
Call Stack (most recent call first):
  cmake/DPF-plugin.cmake:155 (dpf__build_jack)
  examples/Meters/CMakeLists.txt:4 (dpf_add_plugin)

CMake Error at cmake/DPF-plugin.cmake:219 (dpf__target_link_directories):
  dpf__target_link_directories Macro invoked with incorrect arguments for
  macro named: dpf__target_link_directories
Call Stack (most recent call first):
  cmake/DPF-plugin.cmake:155 (dpf__build_jack)
  examples/Meters/CMakeLists.txt:4 (dpf_add_plugin)

CMake Error at cmake/DPF-plugin.cmake:225 (dpf__target_link_directories):
  dpf__target_link_directories Macro invoked with incorrect arguments for
  macro named: dpf__target_link_directories
Call Stack (most recent call first):
  cmake/DPF-plugin.cmake:155 (dpf__build_jack)
  examples/Meters/CMakeLists.txt:4 (dpf_add_plugin)

CMake Error at cmake/DPF-plugin.cmake:302 (dpf__target_link_directories):
  dpf__target_link_directories Macro invoked with incorrect arguments for
  macro named: dpf__target_link_directories
Call Stack (most recent call first):
  cmake/DPF-plugin.cmake:159 (dpf__build_dssi)
  examples/Meters/CMakeLists.txt:4 (dpf_add_plugin)

CMake Error at cmake/DPF-plugin.cmake:206 (dpf__target_link_directories):
  dpf__target_link_directories Macro invoked with incorrect arguments for
  macro named: dpf__target_link_directories
Call Stack (most recent call first):
  cmake/DPF-plugin.cmake:155 (dpf__build_jack)
  examples/MidiThrough/CMakeLists.txt:4 (dpf_add_plugin)

CMake Error at cmake/DPF-plugin.cmake:219 (dpf__target_link_directories):
  dpf__target_link_directories Macro invoked with incorrect arguments for
  macro named: dpf__target_link_directories
Call Stack (most recent call first):
  cmake/DPF-plugin.cmake:155 (dpf__build_jack)
  examples/MidiThrough/CMakeLists.txt:4 (dpf_add_plugin)

CMake Error at cmake/DPF-plugin.cmake:225 (dpf__target_link_directories):
  dpf__target_link_directories Macro invoked with incorrect arguments for
  macro named: dpf__target_link_directories
Call Stack (most recent call first):
  cmake/DPF-plugin.cmake:155 (dpf__build_jack)
  examples/MidiThrough/CMakeLists.txt:4 (dpf_add_plugin)

CMake Error at cmake/DPF-plugin.cmake:206 (dpf__target_link_directories):
  dpf__target_link_directories Macro invoked with incorrect arguments for
  macro named: dpf__target_link_directories
Call Stack (most recent call first):
  cmake/DPF-plugin.cmake:155 (dpf__build_jack)
  examples/Parameters/CMakeLists.txt:4 (dpf_add_plugin)

CMake Error at cmake/DPF-plugin.cmake:219 (dpf__target_link_directories):
  dpf__target_link_directories Macro invoked with incorrect arguments for
  macro named: dpf__target_link_directories
Call Stack (most recent call first):
  cmake/DPF-plugin.cmake:155 (dpf__build_jack)
  examples/Parameters/CMakeLists.txt:4 (dpf_add_plugin)

CMake Error at cmake/DPF-plugin.cmake:225 (dpf__target_link_directories):
  dpf__target_link_directories Macro invoked with incorrect arguments for
  macro named: dpf__target_link_directories
Call Stack (most recent call first):
  cmake/DPF-plugin.cmake:155 (dpf__build_jack)
  examples/Parameters/CMakeLists.txt:4 (dpf_add_plugin)

CMake Error at cmake/DPF-plugin.cmake:302 (dpf__target_link_directories):
  dpf__target_link_directories Macro invoked with incorrect arguments for
  macro named: dpf__target_link_directories
Call Stack (most recent call first):
  cmake/DPF-plugin.cmake:159 (dpf__build_dssi)
  examples/Parameters/CMakeLists.txt:4 (dpf_add_plugin)

CMake Error at cmake/DPF-plugin.cmake:206 (dpf__target_link_directories):
  dpf__target_link_directories Macro invoked with incorrect arguments for
  macro named: dpf__target_link_directories
Call Stack (most recent call first):
  cmake/DPF-plugin.cmake:155 (dpf__build_jack)
  examples/States/CMakeLists.txt:4 (dpf_add_plugin)

CMake Error at cmake/DPF-plugin.cmake:219 (dpf__target_link_directories):
  dpf__target_link_directories Macro invoked with incorrect arguments for
  macro named: dpf__target_link_directories
Call Stack (most recent call first):
  cmake/DPF-plugin.cmake:155 (dpf__build_jack)
  examples/States/CMakeLists.txt:4 (dpf_add_plugin)

CMake Error at cmake/DPF-plugin.cmake:225 (dpf__target_link_directories):
  dpf__target_link_directories Macro invoked with incorrect arguments for
  macro named: dpf__target_link_directories
Call Stack (most recent call first):
  cmake/DPF-plugin.cmake:155 (dpf__build_jack)
  examples/States/CMakeLists.txt:4 (dpf_add_plugin)

-- Configuring incomplete, errors occurred!
See also "/home/rob/git/sandbox/dpf_gui_test/dpf/build/CMakeFiles/CMakeOutput.log".
See also "/home/rob/git/sandbox/dpf_gui_test/dpf/build/CMakeFiles/CMakeError.log".

**Comment by falkTX** [comment]
Fixed in a1995bf89680ce9c5278ebc1421af042987b1250
