### ISSUE TITLE
Implement MIDI output

### ISSUE THREAD

**Issue by pdesaulniers** [DISTRHO/DPF#41]
I plan on making a general-purpose LFO tool someday. I'd need to be able to send MIDI CCs.

**Comment by SpotlightKid** [comment]
@brylie You can already make synth plugins with DPF. They don't usually need MIDI output, only MIDI *input*.

**Comment by falkTX** [comment]
now implemented, check the develop branch.
will be merged to master once I finish a few more things.

**Comment by brylie** [comment]
Cool! Remember the documentatoin ;-)

**Comment by falkTX** [comment]
yes. documentation will come after feature freeze is complete.
