### ISSUE TITLE
How to receive midi keyboard input in standalone mode ?

### ISSUE THREAD

**Issue by SeleDreams** [DISTRHO/DPF#419]
Hi, I've been working on an audio software with DPF and to test if it's working I start with a simple oscillator to test midi input, but at the moment it seems like i am just not receiving any input from my midi keyboard
I'm guessing I need to make it receive input from the specific midi device, but I am not too sure where i'm supposed to set it up for standalone applications

**Comment by falkTX** [comment]
See the calls in https://github.com/DISTRHO/DPF/blob/main/distrho/DistrhoStandaloneUtils.hpp
MIDI support is blocked under some contexts, alike microphone input, so we cant assume to always be there.
For most cases just using `requestMIDI()` in standalone is enough, assuming it is not running under JACK of course.

**Comment by SeleDreams** [comment]
I see, is there a macro or something that would define if it's the standalone build ? and a way to check if it's using jack ?
this way i would call it only when necessary

**Comment by falkTX** [comment]
It is literally the first function there.
```
/**
   Check if the current standalone is using native audio methods.
   If this function returns false, you MUST NOT use any other function from this group.
*/
bool isUsingNativeAudio() noexcept;
```

**Comment by SeleDreams** [comment]
ah yeah, but in this case i meant more at compile time, like a macro because it's only meant to run in standalone mode

**Comment by falkTX** [comment]
JACK is always enabled, with fallback to rtaudio if alsa/pulse is available, or other stuff on win/mac.

**Comment by SeleDreams** [comment]
I see.
Thanks for your help

**Comment by falkTX** [comment]
closing this ticket since the issue was sorted, and was just a question anyhow
