### ISSUE TITLE
release

### ISSUE THREAD

**Issue by dvzrv** [DISTRHO/DPF#42]
It would be great to have a release for dpf, so that it can be properly packaged by downstream distributions. This way plugins using it can depend on it dynamicly.

This would allow me to ship zam-plugins for Arch Linux for example.

**Comment by falkTX** [comment]
The answer for this is a big and clear no. And it won't be changed.
DPF is meant to be included by plugin authors, so they can focus development on a specific version or branch of it. As DPF API eventually breaks, plugins will not be affected.
Also plugin authors might want to do custom additions to DPF, which may or may not be merged back upstream for a variety of reasons.
The power is on the plugin developer to do what they want, I do not want to force a specific DPF code on them.

**Comment by dvzrv** [comment]
@falkTX that's fine by me then!
Was just wondering how to best approach dpf and the plugins that use it.
