### ISSUE TITLE
Support for double precision?

### ISSUE THREAD

**Issue by kiwijam** [DISTRHO/DPF#423]
Hello!

I'm still on the old VST2 SDK but I'd like to move on to newer formats. As far as I can tell, DPF doesn't currently support double precision audio buffers. Any plans for double support?

Thanks!

**Comment by falkTX** [comment]
not really. and honestly not wanted.
64bit/double precision is mostly only needed for very special circunstances, you are free to use that type on internal filters and other DSP, but really there is no point for exposing audio data as double.

see related discussion in:
- https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/73 (thread looks a bit weird as it was imported from and old github ticket) 
- https://www.image-line.com/fl-studio-learning/fl-studio-online-manual/html/app_audio.htm (point 7)
