### ISSUE TITLE
UI modifier key behaviour is broken

### ISSUE THREAD

**Issue by dromer** [DISTRHO/DPF#424]
As discussed on IRC: it seems that modifier keys do not work correctly (shift, ctrl, alt).
Behavior seems to be "inverted" or otherwise incorrect.

This can most directly be observed with the DPF-Widgets test build of DearImGui.
Go to `Inputs, Navigation & Focus` > `Keyboard & Navigation State`.
Press any of the modifier keys: the `Keys mods: ` and `NavInputs down: ` will display after the modifier keys have been released instead of when pressed down.

**Comment by falkTX** [comment]
This was fixed in 044b74cb9326c82375ebd65a2020ad0565a19f8e
