### ISSUE TITLE
How to add context menu to DGL plugin UI?

### ISSUE THREAD

**Issue by AnClark** [DISTRHO/DPF#426]
Hi FalkTX!

I want to add context menu to my plugin UI, so that I can provide some advanced features (e.g. view presets, plugin configurations, etc.). But it seems to be a hard job.

Maybe these ideas worth a try:

1. **Use native menu**: This should be the best solution. It can be achieved via Win32 API on Windows, and GTK on Linux. But seems to be hard for non-GTK applications to use GTK's context menu.
2. **Integrate Dear ImGui:** Is it possible to use Dear ImGui together with picture-based DGL UI?
3. **Create our own context menu like JUCE:** Seems that JUCE has their own context menu implementation.
4. **Use NanoVG:** [Wolf Shaper](https://github.com/wolf-plugins/wolf-shaper) uses NanoVG to implement its own context menu.

Do you have any ideas? Seems that I have to do it from scratch.

**Comment by falkTX** [comment]
That is something to be done on the developer side, DPF only provides a simple window + view.
So rolling your own custom code that mimics the style of a context menu is typically the best choice.

Using gtk or win32 is not a good idea as they can block the main loop and prevent other things from running, resulting in deadlocks.

**Comment by falkTX** [comment]
an alternative that never materialized so far is borderless windows from dpf side, but that seems like abusing things for presenting a non-native menu.
really best to rendering a menu as part of the view, making it so that it also nicely closes together with the view without leaving some weird top-level dangling windows around (a problem that can happen with juce if one is not careful)

**Comment by falkTX** [comment]
integrating imgui on existing dpf UIs is quite straightforward, assuming they use opengl already.
2 examples of this: https://github.com/DISTRHO/DPF-Widgets/blob/main/tests/opengl.cpp and https://github.com/trummerschlunk/master_me/blob/master/plugin/widgets/DoubleClickHelper.hpp

**Comment by AnClark** [comment]
> Using gtk or win32 is not a good idea as they can block the main loop and prevent other things from running, resulting in deadlocks.

Is it possible to use a second thread? Sure that FLTK-based or NTK-based UIs has this issue: when menu is active, even the host is blocked.

**Comment by AnClark** [comment]
> integrating imgui on existing dpf UIs is quite straightforward, assuming they use opengl already.
> 2 examples of this: https://github.com/DISTRHO/DPF-Widgets/blob/main/tests/opengl.cpp and https://github.com/trummerschlunk/master_me/blob/master/plugin/widgets/DoubleClickHelper.hpp

They are based on pure ImGui.

What I'm going to do is to show ImGui window on DGL UI (picture-based). So I can reuse windows and widgets from Dear ImGui (especially sub-windows). Just like this **ideal image** (simply make it with GIMP):

![Image 1](https://github.com/DISTRHO/DPF/assets/12870704/c1137e49-0c40-4c4b-bb5b-6ec268a4c761)

**Comment by AnClark** [comment]
Solved! A good solution is to apply Wolf Shaper's menu widget to my project, just like this:

![image](https://github.com/DISTRHO/DPF/assets/12870704/32f59de3-6d8b-4b9c-ae72-10bcba472b1f)

Source:
- https://github.com/AnClark/Minaton-XT/tree/develop/ext/WolfWidgets
- https://github.com/AnClark/Minaton-XT/blob/develop/plugin/MinatonUIMenu.cpp
