### ISSUE TITLE
Configuration file to override project config/flags?

### ISSUE THREAD

**Issue by mxmilkiib** [DISTRHO/DPF#427]
Basically, I'd like to only ever have DPF build LV2 plugins, whatever the package. (Time, energy, device space, ideology)

I'm thinking like https://archlinux.org/pacman/makepkg.conf.5.html

Or might this alreayd be possible? Thanks!

**Comment by falkTX** [comment]
I dont understand what you are asking

**Comment by falkTX** [comment]
closed due to lack of feedback, also there is no one size fits all for project management, each one will use different things.
and it is not DPF's job to control whatever they use

**Comment by mxmilkiib** [comment]
Sorry, life things happened.

Not sure if you've understand more since your first comment given what you said.

Instead of a config, maybe an environment variable?

I just wish to block any -git package from making non-LV2 copies of plugins.
