### ISSUE TITLE
dgl/src/pugl-upstream point to unexistent commit

### ISSUE THREAD

**Issue by mazes-80** [DISTRHO/DPF#431]
I mostly try to install things via package manager, which is the way for my distro.
One of my self made package "wolf-spectrum" uses dpf as a submodule.

The package manager is a bit picky when checking out submodules, it requires exact matching commit ID to be present.
As a result if I try to install my package on a new host, it fails claiming that 3e03459a5a0b0f118b04e9e0b0a32f42ccd04a5c is not an existing commit.
I still have copies from the repository where it existed on other hosts, if I used these copies, then everything is ok and I can install package.
However until dgl/src/pugl-upstream point to unexisting commit, I cannot share my package in community repositories.

**Comment by falkTX** [comment]
just update dpf then, things are generally ok in terms of backwards compat. or use a source tarball in case wolf-spectrum provides one, not sure if it is the case.

**Comment by mazes-80** [comment]
> just update dpf then, things are generally ok in terms of backwards compat.

There is not much room for user action. The best I can do user side is to force to an existing commit. However forcing to latest pugl commit breaks the compilation. Even latest dpf commit points to same unexistent pugl commit.
I can also fix things from within the package, but this is only ephemeral fixes. Who may lead to troubles with any upstream updates.
  
> or use a source tarball in case wolf-spectrum provides one, not sure if it is the case.

ofc I can use a "versioned" tarball . but then it will not be a "live" package who follows the VCS.


I think some force push to pugl erased the commit dpf points at. I just need to find which commit I need to point at, and if upstream pointed it already, would be more steady in case of any updates.

**Comment by falkTX** [comment]
I think there is some confusion here. this is git, commits are not simply deleted. I sometimes force-push to the pugl fork in order to keep things clean, but that does not delete the commit, it will still be there but simply not be part of a branch anymore.

if you go through github web view for example, you see https://github.com/DISTRHO/pugl/tree/3e03459a5a0b0f118b04e9e0b0a32f42ccd04a5c can be opened and navigated, it simply says "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository." which is indeed true.

I just tried a `git clone --recursive` and it still works fine, so this is just pickiness on the part of the packaging tool.

```
% git clone --recursive git@github.com:wolf-plugins/wolf-spectrum.git
Cloning into 'wolf-spectrum'...
remote: Enumerating objects: 1484, done.
remote: Counting objects: 100% (314/314), done.
remote: Compressing objects: 100% (131/131), done.
remote: Total 1484 (delta 209), reused 247 (delta 174), pack-reused 1170
Receiving objects: 100% (1484/1484), 965.30 KiB | 1.17 MiB/s, done.
Resolving deltas: 100% (841/841), done.
Submodule 'dpf' (https://github.com/DISTRHO/DPF) registered for path 'dpf'
Submodule 'libs/kissfft' (https://github.com/mborgerding/kissfft.git) registered for path 'libs/kissfft'
Submodule 'libs/readerwriterqueue' (https://github.com/cameron314/readerwriterqueue.git) registered for path 'libs/readerwriterqueue'
Cloning into 'wolf-spectrum/dpf'...
remote: Enumerating objects: 27736, done.        
remote: Counting objects: 100% (2879/2879), done.        
remote: Compressing objects: 100% (708/708), done.        
remote: Total 27736 (delta 2236), reused 2754 (delta 2140), pack-reused 24857        
Receiving objects: 100% (27736/27736), 26.80 MiB | 10.33 MiB/s, done.
Resolving deltas: 100% (22991/22991), done.
Cloning into 'libs/kissfft'...
remote: Enumerating objects: 1695, done.        
remote: Counting objects: 100% (99/99), done.        
remote: Compressing objects: 100% (53/53), done.        
remote: Total 1695 (delta 51), reused 76 (delta 45), pack-reused 1596        
Receiving objects: 100% (1695/1695), 994.67 KiB | 7.31 MiB/s, done.
Resolving deltas: 100% (888/888), done.
Cloning into 'libs/readerwriterqueue'...
remote: Enumerating objects: 698, done.        
remote: Counting objects: 100% (110/110), done.        
remote: Compressing objects: 100% (57/57), done.        
remote: Total 698 (delta 61), reused 96 (delta 53), pack-reused 588        
Receiving objects: 100% (698/698), 226.03 KiB | 3.77 MiB/s, done.
Resolving deltas: 100% (392/392), done.
Submodule path 'dpf': checked out '30cf55aa1570553947c0e5add45cf9e6bf4fe1e2'
Submodule 'dgl/src/pugl-upstream' (https://github.com/DISTRHO/pugl.git) registered for path 'dpf/dgl/src/pugl-upstream'
Cloning into 'dpf/dgl/src/pugl-upstream'...
remote: Enumerating objects: 7477, done.        
remote: Counting objects: 100% (1048/1048), done.        
remote: Compressing objects: 100% (151/151), done.        
remote: Total 7477 (delta 974), reused 898 (delta 897), pack-reused 6429        
Receiving objects: 100% (7477/7477), 2.21 MiB | 8.00 MiB/s, done.
Resolving deltas: 100% (5381/5381), done.
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 4 (delta 3), reused 3 (delta 3), pack-reused 1
Unpacking objects: 100% (4/4), 500 bytes | 83.00 KiB/s, done.
From https://github.com/DISTRHO/pugl
 * branch            3e03459a5a0b0f118b04e9e0b0a32f42ccd04a5c -> FETCH_HEAD
Submodule path 'dpf/dgl/src/pugl-upstream': checked out '3e03459a5a0b0f118b04e9e0b0a32f42ccd04a5c'
Submodule path 'libs/kissfft': checked out '8f47a67f595a6641c566087bf5277034be64f24d'
Submodule path 'libs/readerwriterqueue': checked out 'b18136b37edd3ee55369ce647e48474337f4b519
```

**Comment by falkTX** [comment]
well I am closing this as unsupported, using commits that do not belong to a branch anymore is normal for me, as dpf is used as vendored dependency and sometimes releases are made with slightly experimental changes.

for example https://github.com/brummer10/ToneTwistPlugs/releases/ has some tagged releases using WIP pugl-update-v4 branch. as we are still doing some checks/tests, there is code on dpf side that is not quite correct sometimes. after verifying that everything works proper I will squash the branch commits and put them on the dpf develop branch, for a cleaner git history, then delete the old WIP branch.

that means some releases of ToneTwistPlugs will reference dpf commits that are no longer in any active branch.

similar things can happen to dpf use of pugl, where I iterate over things to send upstream and switch back to "stock" upstream matching branch when everything is merged on their side.

I have no intentions of changing this workflow.
