### ISSUE TITLE
Create MOD plug with custom UI

### ISSUE THREAD

**Issue by brummer10** [DISTRHO/DPF#434]
Hi
I wonder if there is a build macro which allow to build a LV2 plug only, regardless of the other build macros set in the makefile, to implement a custom MOD UI. So to say, avoid building any GUI stuff, just build the plugin_dsp.so, the plugin_dsp.ttl and the manifest.ttl  (+preset.ttl) files and add rdfs:seeAlso <modgui.ttl> to the manifest. 
This will allow me add the custom modgui stuff in a build target.
I could properly implement most of this by myself in my makefiles, (just not to avoid the GUI stuff building on dpf side), but wonder if there is already a flag which I didn't know about.

I see there are the options to define DISTRHO_PLUGIN_USES_MODGUI in the PluginInfo.h file, but that one creates a generic modgui.ttl file and implement a generic MOD folder. As well other formats been build then.

**Comment by falkTX** [comment]
sure you can, a simple `make -f plugins/XYZ/Makefile lv2_dsp` shall do the trick if triggered from the main root makefile.
the thing it needs here is the `lv2_dsp` target, which builds only the lv2 dsp side as the name indicates. usually we use `lv2_sep` for getting the UI object too though

for the modgui, the `DISTRHO_PLUGIN_USES_MODGUI` macro simply adds a "seeAlso modgui" to the main ttl, but expects you to create the modgui yourself.

there is a way to get DPF desktop GUIs as modguis, if using opengl2+, it is how cardinal mini and wolfshaper get pushed into MOD. some day I will figure out how to do the same for cairo, but for now that does not work yet.

**Comment by brummer10** [comment]
I may do something wrong, but I end up with:
```
Creating libdgl-cairo.a
make[1]: Leaving directory '/home/brummer/projecte/neuralcapture/dpf/dgl'
make -f plugins/NeuralRecord/Makefile lv2_dsp
make[1]: Entering directory '/home/brummer/projecte/neuralcapture'
plugins/NeuralRecord/Makefile:38: ../../dpf/Makefile.plugins.mk: No such file or directory
make[1]: *** No rule to make target '../../dpf/Makefile.plugins.mk'.  Stop.
make[1]: Leaving directory '/home/brummer/projecte/neuralcapture'
make: *** [Makefile:96: MOD] Error 2
```

Could I set the DISTRHO_PLUGIN_USES_MODGUI macro as well in the makefile? 
Here it generate a generic modgui on top when set in the PluginInfo.hpp file

**Comment by brummer10** [comment]
I end up implementing a BUILD_MOD macro in my plugin makefiles. Was easy enough and works very well. 
I checked it worked well with the mod-plugin-builder, so I'll close this issue.
regards
