### ISSUE TITLE
Fail to use requestParameterValueChange() on host which support it 

### ISSUE THREAD

**Issue by brummer10** [DISTRHO/DPF#435]
branch pugl-update-v4

It seems 
`#define DISTRHO_PLUGIN_WANT_PARAMETER_VALUE_CHANGE_REQUEST 1`
have no effect. 
Parameters wont be updated in the UI. This is on the MOD which usually supports this feature. 
I could use it when implement it directly in a LV2 wrapper,  still, when using it within DPF it refuse to work. 
Related plug source code is here:
https://github.com/brummer10/neuralrecord
maybe I do something wrong?

**Comment by falkTX** [comment]
you are requesting a parameter change right? there is a specific call for this

**Comment by falkTX** [comment]
https://github.com/DISTRHO/DPF/blob/main/distrho/DistrhoInfo.hpp#L569 mentions what to do

**Comment by brummer10** [comment]
Yep, I've done that:
https://github.com/brummer10/neuralrecord/blob/main/plugins/NeuralRecord/DistrhoPluginInfo.h#L29

I hand over the requestParameterValueChange() call to the dsp class here:
https://github.com/brummer10/neuralrecord/blob/main/plugins/NeuralRecord/PluginNeuralCapture.cpp#L21

take it here:
https://github.com/brummer10/neuralrecord/blob/main/plugins/NeuralRecord/profiler.cc#L211
on a std::function call 
https://github.com/brummer10/neuralrecord/blob/main/plugins/NeuralRecord/profiler.h#L150
and use it like this:
https://github.com/brummer10/neuralrecord/blob/main/plugins/NeuralRecord/profiler.cc#L546

**Comment by brummer10** [comment]
Latest commits to the repository fixed this issue. Thanks a lot. So we could close this now.
