### ISSUE TITLE
Window: DGL Cairo has a critical bug on rendering

### ISSUE THREAD

**Issue by AnClark** [DISTRHO/DPF#438]
Hi, falkTX!

I'm testing jpcima's String Machine on Windows. It uses DPF and Cairo. When I open string machine's GUI (VST2) on hosts like REAPER and MidiPlayer6, the GUI will crash occasionally. At this time, the host UI may crash altogether.

![屏幕截图 2022-11-04 155319](https://user-images.githubusercontent.com/12870704/199922570-ebf44ad8-04c9-46d5-bd24-7ec3a8469343.jpg)
![屏幕截图 2022-11-04 155252](https://user-images.githubusercontent.com/12870704/199922636-3a9a81d4-6b4d-4825-b981-b234f162a8f0.jpg)
![屏幕截图 2022-11-04 155230](https://user-images.githubusercontent.com/12870704/199922643-9a3bf9e6-e196-427d-a3bd-2c7bdbfbba1d.jpg)

(Notice the font in the third image, which only appears on critical UI rendering issues.)

This issue may be similar to #437 , but even more critical.

---

System environment:

|Item|Value|
|------|----------|
|OS|Windows 10|
|Build environment|MSYS2 MinGW64|
|Cairo library|Provided by MSYS2|

**Comment by falkTX** [comment]
is the plugin using an updated dpf? if not the bug is invalid, because as I said on the other discussion this same issue was already fixed.

**Comment by AnClark** [comment]
> is the plugin using an updated dpf? if not the bug is invalid, because as I said on the other discussion this same issue was already fixed.

It still uses old DPF (f24e5317). I'll test it later with updated DPF.

**Comment by falkTX** [comment]
the commit comes from pugl, so you cant just cherry-pick it. too many things change, then dpf has to change to match too.

PS: bug reports against old DPF are invalid btw, and kinda waste of time

**Comment by AnClark** [comment]
Thanks a lot! I'll sync the local DPF tree.

P.S.  A change log of critical updates maybe useful.
