### ISSUE TITLE
[CMake] Possibility to link custom libraries (statically)

### ISSUE THREAD

**Issue by relascope** [DISTRHO/DPF#439]
`target_link_libraries` and `dpf__add_static_library` looked good, but won't work, when placed before or after, because all linking has to be in one CMake `target_link_libraries`.    
`DPF/cmake/DPF-plugin.cmake` could be edited, but I prefer not to change code in submodules...

**Comment by falkTX** [comment]
who says that? In https://github.com/DISTRHO/elements-template-plugin/blob/main/CMakeLists.txt I add extra libraries to link without issues, so it for sure works (and CI builds prove it also works for linux, mac and windows too).

**Comment by AnClark** [comment]
`but won't work, when placed before or after,`

What happened? Linker error, or other problems?

I agree with falkTX. I use CMake too, and my projects usually link against 3rd-party libraries. Everything should works well.

You can refer to my project [Minaton-XT](https://github.com/AnClark/Minaton-XT). It links against 2 external libraries statically.

**Comment by relascope** [comment]
Sorry, it works. I forgot to specify `PRIVATE|PUBLIC`.
