### ISSUE TITLE
VST3: first parameter always set to default from save

### ISSUE THREAD

**Issue by isivisi** [DISTRHO/DPF#442]
I'm consistently having issues getting the vst3 build of my plugin to load the first parameter value from a save state. In ableton the value saves fine in save files and presets and everything updates accordingly while using the program, but upon saving and reloading a project the first parameter is always set to its default value.

This also happens in carla when cloning the plugin. Also requestParameterValueChange doesn't work in Carla with vst3

I checked out another plugin ([wolf-shaper](https://github.com/wolf-plugins/wolf-shaper)) and it also had these issues

VST2 works perfectly everywhere

**Comment by falkTX** [comment]
Are you using develop branch? there were some fixes related to this.

**Comment by isivisi** [comment]
I switched to the develop branch and tried it out, still the same issues on both windows and linux. Also I just realized it is setting the value to its minimum value, not the default.

**Comment by isivisi** [comment]
I've narrowed down the issue to DISTRHO_PLUGIN_WANT_MIDI_INPUT being enabled. For vst3 this adds a parameter offset and seemingly causes the issue. Without midi input enabled the first value is properly cloned and loaded from save in carla and bitwig.

**Comment by falkTX** [comment]
That was it! A little typo kinda thing where enum increment was not done properly.
Fixed in 915daad0ac414abfe0a85207ccacd2d3ea871d53

Also saw some hosts not updating component + controller properly at the same time, so fixed that up now too.

**Comment by isivisi** [comment]
Tested, works great! The first value gets brought back fine :)
