### ISSUE TITLE
VST3: Cannot reset params to default or load programs in REAPER

### ISSUE THREAD

**Issue by AnClark** [DISTRHO/DPF#450]
Hi, FalkTX!

I'm porting a VST2 synthesizer Cetone Light to DPF. When I test its VST3 edition in REAPER, I found REAPER can neither load my user presets, nor reset preset to default.

How to produce:

1. Clone [my repo](https://github.com/anclark/cetonesynthlight)
2. Configure with `cmake -S . -B build -DCMAKE_BUILD_TYPE=Release`
3. Add `build/bin` to REAPER's search path
4. Load VST3 plugin
5. Tune any parameter on editor UI, then select "Reset to factory default" in REAPER's preset dropdown. You will see parameters are still in tuned state, not resetting to default.

VST 2.4 edition does not have this problem.

**Comment by AnClark** [comment]
Solved!

That's because I forgot to set `parameter.symbol` in `initParameter()`.

**Comment by falkTX** [comment]
that makes me think an official "selftest" mode is needed, that just verifies that all plugin properties are set correctly..

**Comment by AnClark** [comment]
> that makes me think an official "selftest" mode is needed, that just verifies that all plugin properties are set correctly..

Agree. Selftest is essential. Users may ignore some important properties (like `symbol`).
