### ISSUE TITLE
VST3: Can't automate VST3 parameters in Ardour

### ISSUE THREAD

**Issue by eventual-recluse** [DISTRHO/DPF#458]
This seems to apply to Ardour and not other DAWs, so I'm not sure if it's an Ardour problem, a DPF problem, or a me problem.

I could set up automation on the plugin parameters, until I added MIDI ports to the plugin and changed the run method to the one that includes midi events. After adding MIDI ports and the midi run method, the parameters were no longer available for automation (the option to automate them simply doesn't appear), though they could be changed in Ardour's generic GUI without a problem.

The same VST3 works without any problems in Bitwig Studio and Reaper DAW and the parameters can be automated in both these DAWs. (Also, VST2 can be automated in Ardour without any problem).

(To investigate further, I added a parameter to the example MidiThrough plugin and found the same problem: the parameter can't be automated in Ardour.)

**Comment by falkTX** [comment]
might be a parameter number limit issue on ardour, best to ask them directly.

vst3 doesnt do real midi, so plugin frameworks like dpf and juce fake it through the use of special parameters that get a midi CC assignment.
dpf creates 129 * 16 parameters for all the possible MIDI CC, channel pressure and pitchbend * 16 channels.
after these come the real plugin parameters

all these CC assigned params have the vst3 hidden flag, so they should not appear on hosts.

this is quite a lot of parameters, so maybe ardour is limiting the parameter count and the real parameters never get a chance to appear. if that is indeed the case, a possible fix would for ardour take into account hidden parameters when counting them.

**Comment by x42** [comment]
Yes, by default Ardour only shows automation lines for first 512 parameters (this is configurable at runtime).

However the ugly hack that JUCE does to expose "MIDI CC"s do not count towards that. Ardour special cases those.
MIDI CCs are already shown as automation lanes in Ardour. -- JUCE MIDI CCs Params do not show up in Arodur's generic UI either.

**Comment by x42** [comment]
@falkTX how does DPF name those CCs? Maybe we need a special case like

https://github.com/Ardour/ardour/blob/d2fdd72bc4d54691b5f7baa1bd80584097017bd7/libs/ardour/vst3_plugin.cc#L1464-L1467

**Comment by falkTX** [comment]
the difference with juce is that it puts the parameters first, then the midi ccs. on dpf side it first shows the midi ccs and only after come the real parameters.
I think this makes all the difference



> @falkTX how does DPF name those CCs? Maybe we need a special case like
> 
> https://github.com/Ardour/ardour/blob/d2fdd72bc4d54691b5f7baa1bd80584097017bd7/libs/ardour/vst3_plugin.cc#L1464-L1467

err that is an ugly hack.. why not use `ParameterInfo::kIsHidden` flag for it? dpf sets it for all the midi cc stuff.

**Comment by x42** [comment]
The idea is that the user should never directly interact with MIDI CC control ports. They are bound to actual MIDI events.

I'll add a special case for `"MIDI Ch. %d CC %d"`  -- what is the 2nd variant `"Ch.%d CC%d"` used for?

**Comment by falkTX** [comment]
> what is the 2nd variant `"Ch.%d CC%d"` used for?

that is the short name of the parameter

**Comment by x42** [comment]
Added in Ardour 8.6.275

**Comment by eventual-recluse** [comment]
Aha, yes, if I go to Edit -> Preferences -> Performance and set Automatables to 'unlimited', then reload the plugin, the parameters can be automated.

I'll try the new Ardour to check the fix when I get the chance as well.

Thanks to you both! Much appreciated
