### ISSUE TITLE
double precision processing support

### ISSUE THREAD

**Issue by Soulusions** [DISTRHO/DPF#461]
Currently DPF asserts that all incoming and outgoing samples are 32 bit floats.
However it's also pretty safe to assume that just about every modern host is gonna be running at 64 bit, so I'm wondering how doable it would be for DPF to either offer a templated process function or some kind of "accept 64 bit" compiler flag.

**Comment by dromer** [comment]
32bit audio already has near infinitely low noise floor.
Besides, I don't think there is any DAW that even supports 64bit audio buffers.

I think you might be confusing 64bit CPU architecture with sensible audio word lengths.

**Comment by falkTX** [comment]
> Besides, I don't think there is any DAW that even supports 64bit audio buffers.

most of them do actually. it is actually rare nowadays to have a daw without 64bit/double buffer support.

but in any case, such feature is not wanted in DPF that targets the making of simpler / easier plugins.
same reason as for why there is no multi midi port support.

so I am closing the ticket as not wanted

**Comment by Soulusions** [comment]
Yeah that's totally fair! Thanks for the reply!
