### ISSUE TITLE
States: Allow saving binary data

### ISSUE THREAD

**Issue by sevenc-nanashi** [DISTRHO/DPF#464]
I'm creating a bridge for existing application.

I'd like to use states to save wave data, but looks like the states doesn't allow saving binary data. (I use base64 to serialize)
It would be nice to have ability to save any binary data.

**Comment by falkTX** [comment]
while I understand the wish, I do not want to keep adding features to DPF forever and have it balloon in scope, instead I prefer to reduce scope and goals.

requiring to use strings makes things simple, and also avoids having to deal with endianness conversion among many other topics.
so I am saying no to this.

you can tag a state as being a base64 string binary, there is already a flag for that. but that is as far as I want to go for this.
