### ISSUE TITLE
Stopped working on Reaper 7.27

### ISSUE THREAD

**Issue by sevenc-nanashi** [DISTRHO/DPF#477]
All plugin stopped working on Reaper 7.27 on Windows.

I tried to load example plugins, on both `develop` and `main` branch, but Reaper cannot load them.
![image](https://github.com/user-attachments/assets/c382bcac-d8c0-4c5f-8472-15354a6b5c6a)

**Comment by falkTX** [comment]
without the plugins changing? so it would be a host change that triggers the issue?

**Comment by sevenc-nanashi** [comment]
Yes. These example plugins, and my plugin using DPF, used to be work before the update.

**Comment by dromer** [comment]
On Linux my DPF based plugins still work correctly in Reaper 7.27

**Comment by sevenc-nanashi** [comment]
I resolved the issue; looks like my VCRUNTIME140D was broken because of Weird Visual Studio Installer.
Sorry!
