### ISSUE TITLE
OSX build failure

### ISSUE THREAD

**Issue by zamaudio** [DISTRHO/DPF#5]
using GCC 4.2 with apple patched toolchain:

../../dpf/distrho/src/DistrhoPluginLV2.cpp: In member function 'void DISTRHO::PluginLv2::lv2_run(uint32_t)':
../../dpf/distrho/src/DistrhoPluginLV2.cpp:381: error: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
/usr/lib/apple/SDKs/MacOSX10.5.sdk/usr/include/architecture/i386/math.h:405: note: candidate 1: double fmod(double, double)
/usr/lib/apple/SDKs/MacOSX10.5.sdk/usr/include/c++/4.2.1/cmath:255: note: candidate 2: float std::fmod(float, float)
../../dpf/distrho/src/DistrhoPluginLV2.cpp:557: error: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
/usr/lib/apple/SDKs/MacOSX10.5.sdk/usr/include/architecture/i386/math.h:405: note: candidate 1: double fmod(double, double)
/usr/lib/apple/SDKs/MacOSX10.5.sdk/usr/include/c++/4.2.1/cmath:255: note: candidate 2: float std::fmod(float, float)

**Comment by falkTX** [comment]
I believe this is no longer an issue with latest DPF.
Please test.

**Comment by zamaudio** [comment]
Using latest DPF this issue still exists using MACOS=true MACOS_OLD=true and cross compiler.

**Comment by zamaudio** [comment]
Works now thanks.
