### ISSUE TITLE
DSSI build said not to have an UI (in Carla and Qtractor)

### ISSUE THREAD

**Issue by pdesaulniers** [DISTRHO/DPF#51]
Carla and Qtractor tell me the DSSI build of d_meters from the plugin-examples doesn't have an UI, but it does have one if I open it in Renoise. Same thing with d_states and Wolf Shaper.

Nekobi, MVerb, and the few zam-plugins that I've tried don't have this issue. 

Not sure what's going on here. It seems like only the plugins that use resource files are labeled as having an UI?? Am I missing something obvious? :p

**Comment by falkTX** [comment]
Seems to be due to use of underscores in the plugin name.
A host bug, not in DPF.

**Comment by pdesaulniers** [comment]
Correct! The weird thing is that I actually had to remove all of the hyphens in the file name to get this to work (including "-dssi"). Yet, some other plugins do have this suffix, and the UI shows up without issues.
