### ISSUE TITLE
(LV2) stateChanged callback not always received when showing UI

### ISSUE THREAD

**Issue by pdesaulniers** [DISTRHO/DPF#57]
...and if it is received, it takes a bit of time, compared to the VST and DSSI builds.

This issue can be seen by running Wolf Shaper or ZamSynth, in Carla or Ardour.

This issue doesn't seem to affect everyone. I assume there is some race condition somewhere.

**Comment by falkTX** [comment]
One thing I see is that you are saving your entire state in 1 key.
This can be quite large, if I draw many points the state value can get to thousands of characters long.

**Comment by falkTX** [comment]
also, previous carla versions had issues with large atom buffers and passing messages quickly enough.
for those reporting such issues in carla, tell them to update carla to latest beta first and try again.

**Comment by falkTX** [comment]
Should be fixed now in pugl-update branch. please test.
At least ZamSynth works nicely now (will do a PR against zam-plugins for a few fixes on it)

**Comment by pdesaulniers** [comment]
Even without the fix, I haven't been able to reproduce this in a while... I'm closing this for now.
