### ISSUE TITLE
Suggestion: Convenience function to sync audio frames with midi frames

### ISSUE THREAD

**Issue by diovudau** [DISTRHO/DPF#65]
Have a look at this nested for loop. All it does is syncing midi events to the right audio frame. 

I suggest a function that returns a zipped list of audio and midi frames/events for the current buffer, already in sync. This would be a convenient way to get sample accurate midi handling.

https://github.com/osamc-lv2-workshop/simplesynth/blob/master/plugins/SimpleSynth/PluginSimpleSynth.cpp#L141

**Comment by diovudau** [comment]
```
15:49:01 falktx | question now is.. is it better to have...
15:49:06 falktx | 1. juce like classes, very high level
15:49:22 falktx | 2. util function that returns array of expected events to process
15:49:32 nilshi | util functions
15:49:33 nilshi | 2.
15:49:48 falktx | ie, at frame 0 midi event 1, at frame 32, midi events 3, 4 and 5, etc
15:49:52 nilshi | one can always build up from there later, either on the DPF side or on ones own side.
15:49:55 nilshi | exactly this!
15:50:01 falktx | also option 3, util function to render to the buffer
15:51:20 falktx | the issue with option 2 is that it needs to allocate memory
15:52:20 falktx | can have it prepared before hand, but might happen to lose some events if there are too many of them
15:52:49 nilshi | can this happen in the presented custom solution as well?
15:53:20 falktx | hm?
15:53:44 nilshi | that one loses events, in the code I quoted
15:53:55 nilshi | which is just copy and paste from Kars btw
                | https://github.com/DISTRHO/Kars/blob/master/plugins/Kars/DistrhoPluginKars.cpp#L91
15:54:12 falktx | ah, with that you never lose events
15:54:24 falktx | hmmm hmmm wait
15:54:42 falktx | instead of returning an array, I can return a pointer, in sucession, until it is done processing
15:54:47 falktx | so no allocation
15:55:19 falktx | while (stuff_to_do(&myptr)) { ... handle things here }
15:55:38 falktx | obviously passing midi events there
15:55:53 falktx | can return offset of where to write to, and num of sample to do so
15:55:58 falktx | *samples
```

**Comment by falkTX** [comment]
As a reminder, a test utility class is now in https://github.com/DISTRHO/Kars/blob/master/plugins/Kars/DistrhoPluginKars.cpp#L120
Waiting input, so we can decide if it is good enough already or not.

**Comment by SpotlightKid** [comment]
I've used the `AudioMidiSyncHelper` in [an example plug-in here](https://github.com/osamc-lv2-workshop/simplesynth/blob/develop/plugins/SimpleSynth/PluginSimpleSynth.cpp#L235), and it generally seems to work well, but I also encountered the assertion error mentioned in [Kars issue #1](https://github.com/DISTRHO/Kars/issues/1)

**Comment by falkTX** [comment]
The issues with the class are now fixed in https://github.com/DISTRHO/Kars/commit/8e5dfcd69e1891be1f424b6e2a5874c7aa7f7a44
I made some wrong assumptions initially. should work nicely now, please test and report back. thanks

**Comment by SpotlightKid** [comment]
I've [updated](https://github.com/osamc-lv2-workshop/simplesynth/commit/7fee8dcea1799ba22d1f1521a2c7aa233b172efd) my example synth mentioned above with the new `AudioMidiSyncHelper` [code](https://github.com/osamc-lv2-workshop/simplesynth/blob/develop/plugins/SimpleSynth/AudioSyncHelper.hpp) and so far it seems to work flawlessly.

**Comment by falkTX** [comment]
Cool, thanks for the testing.
Just added this class into a new `DistrhoPluginUtils.hpp` file inside DPF.

**Comment by SpotlightKid** [comment]
Here's the commit for reference: 0e839f08ccfdb5cd12f3363cecd8c8c388828c50
I've updated my example synth plugin to use the new header: https://github.com/osamc-lv2-workshop/simplesynth/commit/6c1cb6552465789bfbf24434feef1a902040c6f3
