### ISSUE TITLE
Need clarification on NanoWidget constructor with NanoWidget* argument

### ISSUE THREAD

**Issue by pdesaulniers** [DISTRHO/DPF#68]
Namely, that one: https://github.com/DISTRHO/DPF/blob/4a4f95fc9f106882c2702fa22c2a574124a3f783/dgl/src/NanoVG.cpp#L945

It allows reusing an existing NanoVG context, which makes sense to me (I don't see the point in using multiple contexts?)

I've added an example to the gl-examples that shows its behavior: https://github.com/pdesaulniers/gl-examples/blob/master/examples/nanovg3.cpp

In the code, I set the absolute location of three rectangles to (100, 100), (200, 200) and (300, 300).

Right now, all the rectangles are getting drawn in the top left corner of the window. The position of the NanoRectangles is effectively ignored:
![2018-09-13-13 28 18](https://user-images.githubusercontent.com/23723605/45504829-e615e600-b758-11e8-895a-2c2c677b8186.png)

However, if I instantiate the rectangles with the `NanoWidget(Widget* groupWidget, int flags)` constructor instead, they appear at the expected location:
![2018-09-13-13 35 28](https://user-images.githubusercontent.com/23723605/45505238-23c73e80-b75a-11e8-9847-54ba43fcd559.png)

Is this the expected behavior?

**Comment by falkTX** [comment]
This is clarified on the upcoming pugl-update-v2 branch by simply not having such constructor available.
Not the best, but at least not confusing.

We can later on do some tests to see if this could be made to work.
I have added your quick test as part of DPF tests, so it will be easy to check if things still work or not.
