### ISSUE TITLE
Allow setting custom widget z-order

### ISSUE THREAD

**Issue by pdesaulniers** [DISTRHO/DPF#89]
Right now, widgets are drawn in the order in which they are created. However, I think it would be useful if we could specify a custom z-order for widgets at runtime.

My approach for this would be to add a setOrder method to the Widget class. Setting the z-order of a widget would cause the parent window to sort the widgets before displaying them. 

(I guess the subwidgets vector in WidgetPrivateData should be sorted too, but I have yet to understand why this vector is needed. See my comment in https://github.com/DISTRHO/DPF/pull/75)

Should I send a pull request for this, or would you rather not have this feature in DGL?

**Comment by falkTX** [comment]
A pushToFront() and pushToBack() could be easily done I guess.
setOrder() implies knowing or exposing the widget stack, which is not trivial.

**Comment by pdesaulniers** [comment]
> setOrder() implies knowing or exposing the widget stack, which is not trivial.

Not sure what you mean by this. I guess something like this would work?
```
void Widget::setOrder(const int zOrder) noexcept
{
    pData->zOrder = zOrder;
    pData->parent._markOrderingAsDirty();
}
```

Then, the window would sort the widgets according to z-order in onPuglDisplay.

**Comment by falkTX** [comment]
I am going to be completely straight here. this seems to me like a terrible idea to add into DPF.
such API would need to go into the order of drawing and events, iterating over all widgets to check an index, or at least maintaining a sortable list.
it adds some complexity to the API that I will not like to have. a call to push to front or back seems okay for me, but not more than this,

**Comment by pdesaulniers** [comment]
OK, pushToFront() and pushToBack() would be good enough. 

Before implementing this, though, I'd like to see what happens to subwidgets in https://github.com/DISTRHO/DPF/pull/75 , since sorting would be different depending on whether the widget's parent is the window or another widget.

**Comment by rghvdberg** [comment]
I'd prefer a simple setZ()

**Comment by falkTX** [comment]
First attempt at https://github.com/DISTRHO/DPF/commits/z-index

**Comment by rghvdberg** [comment]
I tried it, but can't get it to work.
the tooltip has z index 8, the threshold knob has z index 4
![afbeelding](https://user-images.githubusercontent.com/10710663/75088473-d99cdc00-554d-11ea-96a8-33e465418f05.png)

code
https://github.com/rghvdberg/charactercompressor

**Comment by falkTX** [comment]
can you try the other way around?
tooltip z-index 0, knob z-index 4.
might be just the ordering that is wrong

**Comment by falkTX** [comment]
ping for this. I need to get feedback please :)
can I use that plugin project as example, are you still using the newly added API?

**Comment by rghvdberg** [comment]
using the z-index branch, somehow the tooltip is always on top, no matter what I set the z-index to

https://github.com/clearly-broken-software/Punch/blob/master/plugins/Punch/PunchUI.cpp#L76-L94

https://github.com/clearly-broken-software/Punch

**Comment by falkTX** [comment]
SubWidget::toFront() has been added in 597d7f3ee5364970623310305f2d82034fb86348

Should be pretty easy to add a toBack method if necessary, please let me know if you have such usecase.

I am closing this ticket since I do not plan on supporting custom z-index within DPF.
It would get very weird with the way subwidget hierarchy is done anyway.
