### ISSUE TITLE
Different plugin are recognised as same by Carla

### ISSUE THREAD

**Issue by Lyberta** [DISTRHO/DPF#9]
So I'm using Carla to test LV2 plugins but when I compile more than one in one go, the carla lists 2 plugins but when loaded they have the same name and sound. I think this is the case where DistrhoPluginInfo macros get exported into object files shared by plugins.

**Comment by FaTony** [comment]
Ok, the fix is to have unique DISTRHO_PLUGIN_URI for each plugin. I think this info should be put into documentation.

**Comment by falkTX** [comment]
Well, I kinda assumed you already knew this.
LV2 URIs *must be unique*.

**Comment by FaTony** [comment]
I didn't. I never used plugins before. Please update the docs.

**Comment by zamaudio** [comment]
This is a non-issue, feel free to close it.
