### ISSUE TITLE
Scalable UIs - mousewheel/drag delta depends on window size

### ISSUE THREAD

**Issue by zamaudio** [DISTRHO/DPF#95]
I believe the knobs are calibrated based on the window size.  So when you stretch the window, the amount of delta on the drags/wheels is scaled down.  This needs to be independent of the current window size so that the amount of adjustment stays constant at different window sizes.

**Comment by falkTX** [comment]
Indeed.
Do the image-widgets have access to the window scale? We would just need to add a multiplication there...
